### ISSUE TITLE
More flexible pieces size settings

### ISSUE THREAD

**Issue by ww3122000** [dragonflyoss/Dragonfly#1027]
## Why you need it?

Now  DefaultPieceSize is 4M and DefaultPieceSizeLimit is 15M, user can't set it,
There is no entry for the user to configure, maybe the user wants something else

## How it could be?

User can configure with the desired value

**Comment by allencloud** [comment]
Please see https://github.com/dragonflyoss/Dragonfly/blob/master/FAQ.md#what-is-the-size-of-blockpiece-when-distribution

**Comment by allencloud** [comment]
I think we can close this. If you have further question, please do not hesitate to leave a message. @ww3122000
