### ISSUE TITLE
How can I get real ip of cdnnode in logs when I use docker

### ISSUE THREAD

**Issue by YCait** [dragonflyoss/Dragonfly#1033]
## Question

When I use dfget to download files，the ip of cdnnode is always the ip of supernode docker container. How can I get the real cdnnode?

downloading piece:{"taskID":"9627226867cf6d8496944de44f554b8d0d2e743c991da21ad3e05336f01e5ba9","superNode":"125.220.157.228:82","dstCid":"cdnnode:172.20.0.2~9627226867cf6d8496944de44f554b8d0d2e743c991da21ad3e05336f01e5ba9","range":"0-4194303","result":503,"status":701,"pieceSize":4194304,"pieceNum":0}
2019-10-28 02:27:20.073 INFO sign:53-1572229639.942 : remaining piece to be written count:0

**Comment by Starnop** [comment]
@YCait What's mean the real ip of cdnnode. In fact, the IP of supernode is actually the IP of cdnnode. 

>"superNode":"125.220.157.228:82","dstCid":"cdnnode:172.20.0.2~9627226867cf6d8496944de44f554b8d0d2e743c991da21ad3e05336f01e5ba9"

According to the logs above, the IP of supernode is `125.220.157.228` which is the supennode IP that the dfclient can successfully link to the supernode.

**Comment by YCait** [comment]
> @YCait What's mean the real ip of cdnnode? In fact, the IP of supernode is actually the IP of cdnnode.
> 
> > "superNode":"125.220.157.228:82","dstCid":"cdnnode:172.20.0.2~9627226867cf6d8496944de44f554b8d0d2e743c991da21ad3e05336f01e5ba9"
> 
> According to the logs above, the IP of supernode is `125.220.157.228` which is the supennode IP that the dfclient can successfully link to the supernode.

I want the logs to be "cdnnode:125.220.157.228……"

**Comment by Starnop** [comment]
> cdnnode

And then you can set the `advertise-ip` for supernode. And the logs will use the value of you specified instead of the first non-loop address.
