### ISSUE TITLE
supernode failed to start on ipv6 interface

### ISSUE THREAD

**Issue by zhouhaibing089** [dragonflyoss/Dragonfly#1034]
### Ⅰ. Issue Description

```
zhb@box ~
  % supernode --home-dir $(pwd)/.supernode                                                                                                               
Error: peer IP: fe80::1: {"Code":2,"Msg":"invalid value"}
```

### Ⅱ. Describe what happened
When I start supernode on my local machine, it reports error when seeing ipv6 address.

### Ⅲ. Describe what you expected to happen

supernode should be able to start normally.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. `go install github.com/dragonflyoss/Dragonfly/cmd/supernode`
2. run `supernode --home-dir $(pwd)/.supernode` on a machine where ipv6 multicast address is assigned.

### Ⅵ. Environment:

- dragonfly version: HEAD
- OS (e.g. from /etc/os-release): OSX 10.15
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by zhouhaibing089** [comment]
ref https://github.com/dragonflyoss/Dragonfly/issues/334

**Comment by fengzixu** [comment]
Let me check it. /assign me

**Comment by Starnop** [comment]
@fengzixu any updates? 😄

**Comment by fengzixu** [comment]
> @fengzixu any updates? 😄

I will give the conclusion this weekend.

**Comment by fengzixu** [comment]
Hi @Starnop @zhouhaibing089 , after I check related issues. I found there are 3 places which will validate the IP address format:
1.  [https://github.com/dragonflyoss/Dragonfly/blob/master/apis/swagger.yml#L705](https://github.com/dragonflyoss/Dragonfly/blob/master/apis/swagger.yml#L705)
2.  [https://github.com/dragonflyoss/Dragonfly/blob/master/apis/swagger.yml#L807](https://github.com/dragonflyoss/Dragonfly/blob/master/apis/swagger.yml#L807)
3.  [https://github.com/dragonflyoss/Dragonfly/blob/master/apis/swagger.yml#L851](https://github.com/dragonflyoss/Dragonfly/blob/master/apis/swagger.yml#L851)

According to my understanding, for supporting the IPv6 in Dragonfly, we just need to modify the logic of validating IP address in supernode or swagger doc. But I do not ensure that there are other tasks need to be done. @zhouhaibing089 Can you tell me your thoughts about supporting IPv6?

If the task is just modifying the validation, I think I can finish it by GA.

**Comment by Starnop** [comment]
In my opinion, I think it's more of a physical layer thing support for ipv6. Relax the restrictions on IP verification is enough. 
 
In addition, we should make it possible for users to choose whether to support iPv6 according to their own network environment. 

cc/ @fengzixu @zhouhaibing089

**Comment by zhouhaibing089** [comment]
This somehow relates to dual-stack support. What happens if some of clients are on ipv4 and some of them are on ipv6? Will supernode track the ip address family for each client so that it may not return ipv6 peers to ipv4 clients?

**Comment by fengzixu** [comment]
> This somehow relates to dual-stack support. What happens if some of clients are on ipv4 and some of them are on ipv6? Will supernode track the ip address family for each client so that it may not return ipv6 peers to ipv4 clients?

You mean the dfget will run on machines which perhaps were configured IPv4 addr or IPv6 addr.
So we need to support multiple IP format at the same time. Am I right?

**Comment by Starnop** [comment]
> This somehow relates to dual-stack support. What happens if some of clients are on ipv4 and some of them are on ipv6? Will supernode track the ip address family for each client so that it may not return ipv6 peers to ipv4 clients?

Yeah, that's right. And it will bring something difficult. And let's do as @zhouhaibing089 said [here](https://github.com/dragonflyoss/Dragonfly/issues/1038#issuecomment-547743035). @fengzixu 

> Probably we can clearly say that we only support IPv4, and get rid of irrelevant errors to reduce frictions.
