### ISSUE TITLE
how to use dfget command to download general files in the client host (not in the container)

### ISSUE THREAD

**Issue by zjz0924** [dragonflyoss/Dragonfly#1048]
I deployed the dragonfly with Docker.  
Could you please tell me how to use dfget command to download general files outside the container?  likes the command 'docker pull'.

**Comment by orange64** [comment]
I have the same question,when i use 'dfget',it returns `bash: dfget: 未找到命令...`

**Comment by yeya24** [comment]
Thanks for reporting. 
I am sorry that we don't include the dfget binary in the release page. If you want to use dfget outside the container, you can just build it from the source code via `make build-client`, then you get the binary. If you don't want to build the code, you can copy the dfget binary from the dfclient container to your host machine.

If you are seeking for dfget usage, please refer to https://github.com/dragonflyoss/Dragonfly/blob/master/docs/cli_reference/dfget.md.
