### ISSUE TITLE
dfdaemon: when will version 0.5.0 be released

### ISSUE THREAD

**Issue by Fize** [dragonflyoss/Dragonfly#1053]
## Question

we've already used dragonfly in the company, handling some file downloads and doing some custom develpoment.

We are using alicloud image registry service and  we are using uber/kraken pulling images, because dragonfly and kraken are similar, we wanted to use only one in our environment and redeveloping the kraken would waste all of our previous work.  We note that dragonfly currently does not support pulling images from an HTTPS enabled registry and plan to support this feature in Dragonfly 0.5.0, We also see that 1.0.0-alpha is now available, but we don't see commit in this release. Is there a general timeline when this feature will be supported or it is supported in 1.0.0-alpha release and where can I get a guide.

**Comment by Starnop** [comment]
So glad that you are ready to using `dragonfly` as the distribution tools. As for `HTTPS enabled registry`, we have already supported it very early.

FYI: 
+ https://github.com/dragonflyoss/Dragonfly/blob/master/docs/user_guide/docker_proxy.md
+ https://github.com/dragonflyoss/Dragonfly/pull/1028
+

**Comment by Starnop** [comment]
No reply. And close it first. @Fize  If you have any questions. please reopen it.
