### ISSUE TITLE
provide binary files in each release

### ISSUE THREAD

**Issue by yeya24** [dragonflyoss/Dragonfly#1072]
## Why you need it?

Currently, in each release page, there are only links for the images and source code. We should include the binaries (dfget, dfdaemon, supernode) in each release as well.

## How it could be?

We can add release jobs in the CI steps with https://github.com/goreleaser/goreleaser.

**Comment by Starnop** [comment]
It looks so exciting. 😄

**Comment by Starnop** [comment]
And would you like to do that? We can use it in the upcoming version.

**Comment by yeya24** [comment]
Sure. /assign @yeya24
