### ISSUE TITLE
the version 1.0.0 of dfget still have zombie processes after  pull image

### ISSUE THREAD

**Issue by liy516** [dragonflyoss/Dragonfly#1086]
## phenomenon 

[root@dragonfly01 dragonfly]# docker ps 
CONTAINER ID        IMAGE                                 COMMAND                  CREATED             STATUS              PORTS                      NAMES
99b11e0b94f0        192.168.56.102/common/dfclient:1.0.0   "/opt/dragonfly/df-c…"   22 minutes ago      Up 6 minutes        0.0.0.0:65001->65001/tcp   dfclient
[root@dragonfly01 dragonfly]# ps -ef | grep dfget
root      5039  4919  0 10:58 ?        00:00:00 [dfget] <defunct>
root      5052  4919  0 10:58 ?        00:00:00 [dfget] <defunct>
root      5057  4919  0 10:58 ?        00:00:00 [dfget] <defunct>
root      5063  4919  0 10:58 ?        00:00:00 [dfget] <defunct>
root      5604  2456  0 11:05 pts/0    00:00:00 grep --color=auto dfget

**Comment by fengzixu** [comment]
Can you fill the re-produce method in this issue? I think it is beneficial for investigating the problem.

**Comment by zcc35357949** [comment]
https://github.com/dragonflyoss/Dragonfly/blob/master/dfget/core/uploader/peer_server_executor.go#L75
https://github.com/dragonflyoss/Dragonfly/blob/master/dfget/core/uploader/peer_server_executor.go#L79

**Comment by liy516** [comment]
> Can you fill the re-produce method in this issue? I think it is beneficial for investigating the problem.

Pulling a new mirror produces the same number of zombie processes as the number of levels of the mirror.

**Comment by liy516** [comment]
> https://github.com/dragonflyoss/Dragonfly/blob/master/dfget/core/uploader/peer_server_executor.go#L75
> https://github.com/dragonflyoss/Dragonfly/blob/master/dfget/core/uploader/peer_server_executor.go#L79
> Locking after checking server seems to lead this.
You have submitted a PR, I try to  compile your code and test it.
