### ISSUE TITLE
api文档中介绍的taskId的生成及taskUrl的问题

### ISSUE THREAD

**Issue by kisson666** [dragonflyoss/Dragonfly#110]
1.文档中taskUrl是什么，与rawUrl是什么关系？
2.文档中说taskId的生成用到了rawUrl，但是实际代码中taskId的生成没用到源url，而是用到了taskUrl。

**Comment by lowzj** [comment]
1. taskUrl是rawUrl经过处理过后的url，即过滤掉`--filter`中指定的请求参数后的url。
2. taskUrl参与taskId的生成

**Comment by Starnop** [comment]
Has been solved, so close it now.
