### ISSUE TITLE
Add yamlint in CI system for all the yaml files in this repo

### ISSUE THREAD

**Issue by allencloud** [dragonflyoss/Dragonfly#1112]
## Why you need it?

<img width="729" alt="23631;"29031;2019-12-01.19979;"21320;"7 00 00-13"src="https://user-images.githubusercontent.com/9465626/69912997-d32a2700-146c-119412-647870p6">

// <img width="729" alt="屏幕快照 2019-12-01 下午7 00 13" src="https://user-images.githubusercontent.com/9465626/69912997-d32a2700-146c-11ea-9412-64787cc72506.png"> 

## How it could be?

In CI system, when we have a yml file not formatted, error reported.
## Other related information

***!!!!WE STRONGLY ENCOURAGE YOU TO DESCRIBE YOUR ISSUE IN ENGLISH!!!!***

**Comment by allencloud** [comment]
@fengzixu we need to first add ymalint in pouchlinter, I think. https://github.com/pouchcontainer/pouchlinter

**Comment by fengzixu** [comment]
> @fengzixu we need to first add ymalint in pouchlinter, I think. https://github.com/pouchcontainer/pouchlinter

Let me add it.

**Comment by fengzixu** [comment]
add yamllint to pouchlinter: https://github.com/pouchcontainer/pouchlinter/pull/21

**Comment by allencloud** [comment]
> add yamllint to pouchlinter: pouchcontainer/pouchlinter#21

@fengzixu I have merged your pull request. Now you can use image `pouchcontainer/pouchlinter:v0.2.6` to modify the circle ci config.yml.

In addition, I am planning to migrate project github.com/pouchcontainer/pouchlinter to github.com/dragonflyoss/linter . I wish to hear what you think of it. @lowzj @yeya24 @Starnop

**Comment by yeya24** [comment]
I agree to host this lint image in dragonflyoss.  But how? Just fork the pouchlinter repo?

**Comment by allencloud** [comment]
> I agree to host this linter image under dragonflyoss org. But how? Just fork the pouchlinter repo?

I could migrate or transfer that to this org. @yeya24

**Comment by zhouhaibing089** [comment]
@allencloud: Why dragonflyoss/linter and not pouchcontainer/linter?
