### ISSUE TITLE
What is the difference between P2P and CDN download modes in dfget?

### ISSUE THREAD

**Issue by LeslieSun** [dragonflyoss/Dragonfly#1132]
## Question
From the source code, if the pattern is P2P, it will start the dfget server to pull up the peer server service. If it fails, it will change the pattern to CDN. But in the download, only the source is distinguished. P2P and CDN are processed in the same logical branch. Here are two problems. The first one is the difference between P2P mode and CDN mode. The second code has the possibility of failing to create peer server and turning into CDN mode, so there is no problem in the same processing logic of P2P and CDN (P2P mode needs to use peer server service). Please Ask me what's wrong with my understanding. Please advise me

// 从源码中看如果Pattern是p2p会启动dfget server 拉起peer server 服务，如果失败的话就将Pattern改为CDN。但是在download中只区分了Source,P2P和CDN是同一个逻辑分支处理的，这里就引出两个问题，第一就是P2P模式和CDN模式的区别，第二代码的逻辑存在创建peer server失败转为CDN模式的可能，这样P2P和CDN同样的处理逻辑不是存在问题吗（P2P模式是需要使用peer server服务的），请问我的理解哪里出现了问题，请指教

***!!!!WE STRONGLY ENCOURAGE YOU TO DESCRIBE YOUR ISSUE IN ENGLISH!!!!***

**Comment by LeslieSun** [comment]
看来这里靠不住了，只能自己啃源码了

**Comment by Starnop** [comment]
Sorry for the delayed reply. 

In the P2P pattern, dfget will play two roles
+ downloader, which is downloaded from other nodes through P2P
+ uploader, provide file upload service for other nodes to download files from this node

And if dfget failed to start a dfget server which for upload files, it cannot play the role of `uploader`. However, the dfget can still download files through P2P. And that's what we call the CDN pattern which only downloads files from P2P networks, but not uploads files for other peer nodes.

In addition, the processing logic of P2P and CDN is not exactly the same. 
In P2P pattern, dfget needs to report the downloaded piece to the `dfget server` and back up the downloaded file locally, etc.

If you have any more questions, please let us know. And we will reply you soon.
