### ISSUE TITLE
supernode确定是按照piece去源下载内容而不是完整下载？

### ISSUE THREAD

**Issue by LeslieSun** [dragonflyoss/Dragonfly#1142]
## Question
supernode从源下载文件应该是通过TriggerCDN实现的吧，在接口内先判断文件是否存在，如果文件已经存在（且完整）startPieceNum 值为-1，否则为其他值，但是看代码貌似只能为0啊，最后就是完整下载整个文件，而不是想你们说supernode下载一个piece后dfget就能开始下载该piece了，我哪里理解有问题，请指教啊。

**Comment by Starnop** [comment]
ref： https://github.com/dragonflyoss/Dragonfly/blob/master/supernode/daemon/mgr/cdn/cache_detector.go#L57

**Comment by LeslieSun** [comment]
之前的理解以为是你们是按照piece去请求源的，下载下来一个piece就可以提供给dfget去下载了，现在看应该是请求的时候直接下载整个文件（不考虑已经缓存了部分range的数据），在接受数据时，接受满一个piece就可以让dfget来下载了，是这样吗？

**Comment by LeslieSun** [comment]
> ref： https://github.com/dragonflyoss/Dragonfly/blob/master/supernode/daemon/mgr/cdn/cache_detector.go#L57

之前的理解以为是你们是按照piece去请求源的，下载下来一个piece就可以提供给dfget去下载了，现在看应该是请求的时候直接下载整个文件（不考虑已经缓存了部分range的数据），在接受数据时，接受满一个piece就可以让dfget来下载了，是这样吗？

**Comment by LeslieSun** [comment]
> ref： https://github.com/dragonflyoss/Dragonfly/blob/master/supernode/daemon/mgr/cdn/cache_detector.go#L57

之前的理解以为是你们是按照piece去请求源的，下载下来一个piece就可以提供给dfget去下载了，现在看应该是请求的时候直接下载整个文件（不考虑已经缓存了部分range的数据），在接受数据时，接受满一个piece就可以让dfget来下载了，是这样吗？

**Comment by Starnop** [comment]
> 是按照piece去请求源的

如果源支持range 请求，则supernode 会像源请求 range[breakNum*PieceSize - totalSize] 区间的内容；否则是请求range[0 - totalSize]也就是整个文件。无论如何，supernode 只会请求一次。

> 下载下来一个piece就可以提供给dfget去下载了

这句话是正确的，supernode 拿到数据流后，会分片读取，每读取并写入到文件系统一个分片，该分片就可以提供服务。

**Comment by Starnop** [comment]
If you don't have more questions, could you please close this issue? THX.
