### ISSUE TITLE
some node have long time to pull image

### ISSUE THREAD

**Issue by JiaDong007** [dragonflyoss/Dragonfly#1143]
## Question

I use pssh to pull a image of 5G in parallel through 100 nodes,it costs more than 20 minute on average,some need more time.What is the reason?if i use dragonfly on 20 nodes may need 6 minute,
Q1:How to distinguish between mirroring through p2p pattern or CDN pattern？
like this？docker exec dfclient grep 'downloading piece' /root/.small-dragonfly/logs/dfclient.log | grep -v cdnnode
Q2：what is mean?
2019-12-26 08:53:22.437 WARN sign:10 : peerID: 573ce53f939e-172.0.89.2-1577350372688863279 got errors for 8 times which reaches error limit: 5 for taskID(17fcfee1f44f9ea78185176bda16294c0e4c83032310873f167aa96133e809a6)

**Comment by Starnop** [comment]
> I use pssh to pull a image of 5G in parallel through 100 nodes,it costs more than 20 minute on average,some need more time.What is the reason?if i use dragonfly on 20 nodes may need 6 minute,

Could you please add more descriptions about your environment?

> How to distinguish between mirroring through p2p pattern or CDN pattern？
like this？docker exec dfclient grep 'downloading piece' /root/.small-dragonfly/logs/dfclient.log | grep -v cdnnode

Please refer to https://github.com/dragonflyoss/Dragonfly/issues/1132#issuecomment-564399599.

> Q2：what is mean?
2019-12-26 08:53:22.437 WARN sign:10 : peerID: 573ce53f939e-172.0.89.2-1577350372688863279 got errors for 8 times which reaches error limit: 5 for taskID(17fcfee1f44f9ea78185176bda16294c0e4c83032310873f167aa96133e809a6)

That means the peer(573ce53f939e-172.0.89.2-1577350372688863279) failed to download files form other peers for  8 times. And it will download files form supernode directly.

**Comment by JiaDong007** [comment]
Shouldn't p2pmode have more nodes or be faster or stay the same?Why do i  spend more time with more nodes after use dragonfly?@Starnop

**Comment by JiaDong007** [comment]
I pull the dragonflyoss/supernode:1.0.0 and dragonflyoss/dfclient:1.0.0 form dockerHub,it works for me.
