### ISSUE TITLE
In case of data source exception, the task in progress on supernode will not be terminated automatically

### ISSUE THREAD

**Issue by yangchuan37326** [dragonflyoss/Dragonfly#1150]
1. Dfget downloads files through supernode

// 1、dfget通过supernode下载文件 

Expected results:

// 期望结果：

***!!!!WE STRONGLY ENCOURAGE YOU TO DESCRIBE YOUR ISSUE IN ENGLISH!!!!***

**Comment by Starnop** [comment]
I will fix this in the PR #1152 .

**Comment by Starnop** [comment]
@yangchuan37326 Cloud you please have a review for the PR #1152. THX.
