### ISSUE TITLE
Downloading the layers paralyzingly

### ISSUE THREAD

**Issue by wrfly** [dragonflyoss/Dragonfly#119]
![](https://raw.githubusercontent.com/alibaba/Dragonfly/master/docs/images/dfget-combine-container.png)

We know that the download speed between the clients(dfget proxy) is fast, but in some scenarios (for example, sync images between a registry and a mirror registry), I need to speed up part 3️⃣. Cause the registry may running in AWS and the `cluster manager` can be set up in our office, and the network between them is not good (packet losing, latency). And in some cases, docker will stuck in downloading layers, a single stuck can block the whole image, and we have to interrupt the pull process and the files we already download will missing and we have to retry and retry. 

So, if the `cluster manager` can download the layer (or file or block) paralyzingly, we can easily retry the "stuck" part, no need to interrupt the whole downloading process.

In my scenario, I use the `cluster manager` to speed up the process between the remove registry in AWS and the local registry mirror. So the docker daemon have no extra configuration but adjust the DNS record.

**Comment by lowzj** [comment]
Dragonfly downloads every layer of an image individual and caches them locally always.
