### ISSUE TITLE
[Question] How to guarantee the data integrity of the images and the blocks?

### ISSUE THREAD

**Issue by allencloud** [dragonflyoss/Dragonfly#1205]
## Question

today, the block format does not appear to include a checksum and I think that this could potentially lead to a bad block (either through corruption or alternatively via a malicious actor) being distributed through the P2P network and potentially poisoning the cache.   

You mentioned in the SIG presentation that there were some protections for this but I could not understand the specifics.

Would it be possible to explain how the data integrity of the images and the blocks are maintained please?

**Comment by allencloud** [comment]
> the block format does not appear to include a checksum.

No, the block format does not include a checksum.

However, for each distributing file, we record all blocks' checksum into a separate file, which is named by **block metadata file**.

## What is a block metadata file?

Each block metadata file maps each distributing file. The block metadata file includes the following three parts:
* every block's MD5 info;
* the whole distributing file's MD5 info;
* the SHA1 info of the above data;


## How is a block metadata file produced?

Here is the procedure of how to produce a metadata file in Dragonfly:
* **STEP1:** When dfget agents trigger to distribute a file, Supernode makes the CDN manager to download the target file. 
* **STEP2:** As downloading the file, CDN manager will cut the file into blocks.
* **STEP3:** Each time finishing to produce a block, the CDN manager would calculate MD5 for the block, and the store the MD5 in memory.
* **STEP4:** When finishing to calculate all MD5 for all blocks, the CDN manager will continue to calculate MD5 for the downloading file.
* **STEP5:** The CDN manager continues to calculate SHA1 of all calculated MD5 values.
* **STEP6:** The CDN managers write **each block's MD5**, **the whole file's MD5** and **SHA1 of all MD5 values** into the block metadata file.

The following is the brief example of a block metadata file:

blablabla


## How is a block metadata file consumed?

Here is the procedure of how to consume a metadata file in Dragonfly:
1. When distributing a block to a peer, supernode will fetch the MD5 of this block and send this MD5 to peer along with block;
2. After finishing to download the block and MD5, dfget will generate another MD5 of the downloaded block, and check the newly-generated MD5 value with downloaded MD5 value. 
3. If they match, we can trust the data integrity. If they don't match, dfget will report this mismatch to supernode including block info and incorrect peer, and then dfget will try to download the block from other peers;
4. Supernode gets aware of which peer providing incorrect data integrity, and then supernode isolates this peer from the whole peer network.


dragonfly服务端会将分片的checksum记录在一个单独的文件内，分片元信息文件；该文件内保存了每个分片的md5，以及整个镜像文件的md5，同时为了防止该元文件被篡改，记录上述数据
sha1值。服务端在读取元信息文件时，会校验sha1值，若不匹配则会重新回源下载。服务端在分配每个分片信息给dragonfly客户端(peer节点)时，同时会将分片md5值也下发下去。客户端在下载完一个分片后，会进行md5比对校验，以保证数据的正确性。若分片md5校验不通过，则会上报给服务端，同时会重试到其他peer节点。服务端会将该错误的peer节点加入黑名单，从p2p网络中剔除出去。

**Comment by chira001** [comment]
Thank you for the comprehensive response - this clarifies the process well.

**Comment by allencloud** [comment]
I think we could add this into the FAQ or a separate documentation.
