### ISSUE TITLE
How to configure multiple harbor for registry mirror

### ISSUE THREAD

**Issue by haosdent** [dragonflyoss/Dragonfly#1243]
## Question

How to configure multiple harbor for registry mirror?

**Comment by allencloud** [comment]
Here we have a doc: https://github.com/dragonflyoss/Dragonfly/blob/master/docs/user_guide/docker_proxy.md

**Comment by haosdent** [comment]
@allencloud thanks for your reply, but according to https://github.com/dragonflyoss/Dragonfly/issues/525

> , if Dragonfly is configured as an HTTPS proxy, the powerful role of Dragonfly's P2P will be useless.

It would not take advantage P2P of use HTTPS proxy?

**Comment by lowzj** [comment]
The later pr resolves this problem, you can config the property `hijack_https` to hijack the https request of downloading layer.

**Comment by haosdent** [comment]
thx @lowzj @allencloud
