### ISSUE TITLE
Why double the supernode list

### ISSUE THREAD

**Issue by xiaoanyunfei** [dragonflyoss/Dragonfly#1250]
## Question

Why double the supernode list here?

https://github.com/dragonflyoss/Dragonfly/blob/master/dfget/core/core.go#L283

> 	func adjustSupernodeList(nodes []string) []string {
	switch nodesLen := len(nodes); nodesLen {
	case 0:
		return nodes
        case 1:
		return append(nodes, nodes[0])
	default:
		util.Shuffle(nodesLen, func(i, j int) {
			nodes[i], nodes[j] = nodes[j], nodes[i]
		})
		return append(nodes, nodes...)
	}

**Comment by lowzj** [comment]
It's a simple retry mechanism when errors happened.

**Comment by xiaoanyunfei** [comment]
> It's a simple retry mechanism when errors happened.

Thank you
