### ISSUE TITLE
how to confirm image distribution is happening form peer nodes?

### ISSUE THREAD

**Issue by sivakkr** [dragonflyoss/Dragonfly#1265]
## Question
when i verified confirm image download happening from peer, pieceSize:0 pieceNum:0. Is this an error?. Is there any other way to confirm P2P networking is happening?.

**Comment by lowzj** [comment]
here is the method to check: https://github.com/dragonflyoss/Dragonfly/blob/master/FAQ.md#how-to-check-if-block-piece-is-distributed-among-dfgets-nodes
