### ISSUE TITLE
Failed to start the container through the official supernode image of version 1.0.0

### ISSUE THREAD

**Issue by babywaiting** [dragonflyoss/Dragonfly#1295]
### Ⅰ. Issue Description
通过官方1.0.0版本supernode镜像启动容器，命令如下：
docker run -d --name supernode-fastuse6  -p 8001:8001 -p 8002:8002     dragonflyoss/supernode:1.0.0 -Dsupernode.advertiseIp=10.19.10.26
supernode容器无法启动，如果镜像更换为0.3.0的话，就能正常启动容器。

### Ⅱ. Describe what happened
[root@host-10-19-10-27 ~]# docker run -d --name supernode-fastuse6  -p 8001:8001 -p 8002:8002     dragonflyoss/supernode:1.0.0 -Dsupernode.advertiseIp=10.19.10.26
Unable to find image 'dragonflyoss/supernode:1.0.0' locally
1.0.0: Pulling from dragonflyoss/supernode
e7c96db7181b: Pull complete
f3e592039a02: Pull complete
732fc164a4e9: Pull complete
9f7e9ef19193: Pull complete
8ad341464c5b: Pull complete
febadde8e5ce: Pull complete
Digest: sha256:08e3b920c5b68a3612efee20dc8b6088e80c568a18c454ea9524824c73b8defa
Status: Downloaded newer image for dragonflyoss/supernode:1.0.0
8b6ade4efb935bc50f822d92b0ffd478013a1299c7e95fcd790cc77bdd05df51
[root@host-10-19-10-27 ~]# docker ps
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS              PORTS                      NAMES
d715c0c5625f        dragonflyoss/dfclient:v0.3.0   "/dfclient/dfdaemon …"   22 hours ago        Up 5 hours          0.0.0.0:65001->65001/tcp   dfclient-fastuse5
[root@host-10-19-10-27 ~]# docker ps
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS              PORTS                      NAMES
d715c0c5625f        dragonflyoss/dfclient:v0.3.0   "/dfclient/dfdaemon …"   22 hours ago        Up 5 hours          0.0.0.0:65001->65001/tcp   dfclient-fastuse5
[root@host-10-19-10-27 ~]# docker logs supernode-fastuse6
Error: unknown shorthand flag: 's' in -supernode.advertiseIp=10.19.10.26
time="2020-04-22T12:16:52Z" level=error msg="unknown shorthand flag: 's' in -supernode.advertiseIp=10.19.10.26"
[root@host-10-19-10-27 ~]#

### Ⅵ. Environment:

- dragonfly version:1.0.0
- OS (e.g. from /etc/os-release):
NAME="Red Hat Enterprise Linux Server"
VERSION="7.5 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.5"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.5 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.5:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.5
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.5"
- Kernel (e.g. `uname -a`):
Linux host-10-19-10-26 3.10.0-862.el7.x86_64 #1 SMP Wed Mar 21 18:14:51 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by lowzj** [comment]
The parameter of `1.0.0` is different from `0.4.3`, you can get the docker command in this document:
https://github.com/dragonflyoss/Dragonfly/blob/master/docs/ecosystem/Harbor-with-Dragonfly.md#step-1-deploy-dragonfly-server-supernode
