### ISSUE TITLE
Does Dragonfly support P2P Peer Optimal Algorithm based on network topology awareness?

### ISSUE THREAD

**Issue by duyanghao** [dragonflyoss/Dragonfly#1311]
## Question
I am curious about whether Dragonfly supports P2P Peer Optimal Algorithm, guess Peer1 can get data from neither Peer2 or Peer3, and Peer2 is closer to Peer1 with regard to network topology, will Peer1 finally choose the Peer2 instead of Peer3?

**Comment by lowzj** [comment]
Dragonfly uses the minimum load priority algorithm to schedule peers, it doesn't support the P2P Peer Optimal Algorithm now. 
Dragonfly provides a pluggable way to implement customized scheduler, [supernode/plugins](https://github.com/dragonflyoss/Dragonfly/tree/master/supernode/plugins). It may be a little complicated to customize a plugin for now. But a plan(see #1309 ) is on the fly to integrate customized plugin easily.

**Comment by duyanghao** [comment]
> Dragonfly uses the minimum load priority algorithm to schedule peers, it doesn't support the P2P Peer Optimal Algorithm now.
> Dragonfly provides a pluggable way to implement customized scheduler, [supernode/plugins](https://github.com/dragonflyoss/Dragonfly/tree/master/supernode/plugins). It may be a little complicated to customize a plugin for now. But a plan(see #1309 ) is on the fly to integrate customized plugin easily.

What's the plan for this feature? Or doesn't Dragonfly want to support it at all? What do you think of this feature?

**Comment by lowzj** [comment]
I think that it's a very good feature for Dragonfly. Welcome to submit a proposal or pull request to implement it.

Dragonfly team plans to make it pluggable for developers and users to customize their own implementation of some components, and accepts good enhancements and features into master branch.

**Comment by duyanghao** [comment]
@lowzj Thanks for your reply. Close this issue since now I have no idea about this.
