### ISSUE TITLE
ci: builds on travis-ci always fail

### ISSUE THREAD

**Issue by lowzj** [dragonflyoss/Dragonfly#1337]
### Ⅰ. Issue Description

https://travis-ci.org/github/dragonflyoss/Dragonfly/builds/685202340#L196

```
build github.com/dragonflyoss/Dragonfly/cmd/dfget: cannot load github.com/beorn7/perks/quantile: Get https://goproxy.onetool.net/github.com/beorn7/perks/@v/v1.0.0.zip: stopped after 10 redirects
```

**Comment by SataQiu** [comment]
Maybe related to goproxy `goproxy.onetool.net` 😕

**Comment by yeya24** [comment]
I think it is okay to remove travis CI since there is already circle CI there.

**Comment by lowzj** [comment]
> Maybe related to goproxy `goproxy.onetool.net` 😕

Maybe. But I don't understand, I set the `GOPROXY=https://proxy.golang.org`, it seems to not work.

**Comment by lowzj** [comment]
> I think it is okay to remove travis CI since there is already circle CI there.

maybe, it's time to end its life.

**Comment by lowzj** [comment]
> > I think it is okay to remove travis CI since there is already circle CI there.
> 
> maybe, it's time to end its life.

Maybe, it can be rescued again.
It can help us to discover some errors that are not easy to detect.

The current `docker build` command doesn't pass the `GOPROXY` env variable to the building container.
