### ISSUE TITLE
[RFC] Add image-service to dragonfly project

### ISSUE THREAD

**Issue by bergwolf** [dragonflyoss/Dragonfly#1365]
Hi,

We have opened a new issue in the dragonflyoss/community repository to request for inclusion for an image-service project as subsidiary project of dragonfly[1]. It aims at container image acceleration at the client side and defines a custom image format to do so. The OCI community is actively discussing new OCI image spec and the project can serve as a reference implementation for the discussion.

Please share your options and comments. Thanks!

[1] https://github.com/dragonflyoss/community/issues/9

**Comment by Starnop** [comment]
DONE.

**Comment by Starnop** [comment]
Reference: https://github.com/dragonflyoss/image-service

**Comment by bergwolf** [comment]
Thank you all dragonfly community members! We have just pushed the new image service source code to https://github.com/dragonflyoss/image-service. Look forward to helping more Dragonfly users to access container images fast, securely and easily!
