### ISSUE TITLE
supernode增加存储驱动(storage driver)

### ISSUE THREAD

**Issue by nonly** [dragonflyoss/Dragonfly#139]
**背景**
- 当前版本的supernode是将元信息存储在本地内存中；规模比较大时本地内存占用可能过多。

**想法**
- 希望增加一些常用存储的storage driver，例如redis等；用户可以根据需求选择不同的driver存储元信息；
- 目标是：可配置，可插拔，支持多种driver

**Comment by zhouhaibing089** [comment]
Looks very straightforward to replace all the `ConcurrentHashMap` with an interface.

**Comment by allencloud** [comment]
First of all, thanks sincerely for constantly using and supporting Dragonfly. We will try our best to keep Dragonfly better, and keep community and eco-system growing. 

To get more feedback of Dragonfly's adoption in industry, would you mind helping comment in issue https://github.com/dragonflyoss/Dragonfly/issues/306 to give more information about your enterprise's Dragonfly usage. Thanks a lot in advance. @nonly

**Comment by nonly** [comment]
@allencloud  OK, I have commented.

**Comment by Starnop** [comment]
Has been implemented. So close it now.
