### ISSUE TITLE
unit test failed in all probability in CI environment when pull request 

### ISSUE THREAD

**Issue by YesterdayxD** [dragonflyoss/Dragonfly#1416]
### Ⅰ. Issue Description

unit test failed in all probability in CI environment when pull request 

### Ⅱ. Describe what happened
unit test printed the following error:
FAIL: TestSuite/TestReleaseBuffer

### Ⅲ. Describe what you expected to happen
unit test passes

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. run unit test
2.
3.

### Ⅴ. Anything else we need to know?
Chencheng Zhou refered to the following comment about the GET method of the Type Pool in Dragonfly DingDing DevGroup.
```
// Get selects an arbitrary item from the Pool, removes it from the
// Pool, and returns it to the caller.
// Get may choose to ignore the pool and treat it as empty.
// Callers should not assume any relation between values passed to Put and
// the values returned by Get.
//
// If Get would otherwise return nil and p.New is non-nil, Get returns
// the result of calling p.New.
func (p *Pool) Get() interface{}
```

### Ⅵ. Environment:

- dragonfly version: master 
- OS (e.g. from /etc/os-release): CI environment(I am not sure)
- Kernel (e.g. `uname -a`): CI environment ((I am not sure)
- Install tools:
- Others:

**Comment by jim3ma** [comment]
@lowzj PTAL
