### ISSUE TITLE
Feature : Df-daemon support multi-registrys

### ISSUE THREAD

**Issue by mushixun** [dragonflyoss/Dragonfly#142]
In the actual production environment, there will be multiple registrys providing services. These 
registrys provide different types of image downloads according to requirements. However, when a 
computing node downloads images through df-daemon, only one Registry address can be specified, 
and another Registry is required. The df-daemon must be reconfigured and restarted. This is 
unacceptable for the production environment. I hope df-daemon provides support for multiple 
Registry. If the first Registry configured cannot find the image, it will use another Registry.

**Comment by mushixun** [comment]
@zhouhaibing089 OK！There are a lot of registry in our company, computing nodes are mixed to run different applications, and the images of these applications may be distributed in different registry, and the registry parameter of df-daemon can only point to 1 registry, to point to another registry only modify the configuration and restart the df-daemon, so I implemented the issue.
sample : df-daemon --registry registry.example.com

**Comment by allencloud** [comment]
Should this be included in dfget side? @mushixun @zhouhaibing089 @fengzixu

**Comment by lijianfeng1993** [comment]
I have the same requirement.

**Comment by mushixun** [comment]
@allencloud I think to do this in dfget is better

**Comment by zhouhaibing089** [comment]
Could we have a proposal first?

**Comment by Starnop** [comment]
Has been solved. The related PR : #410 #486
