### ISSUE TITLE
When only loopback is found, provide a clear error message.

### ISSUE THREAD

**Issue by eatwithforks** [dragonflyoss/Dragonfly#1428]
## Why you need it?

on my node, the container shows only the loopback address
```
bash-4.4# ifconfig
lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
```

so when i start up the supernode server, i get an error message:

```
Error: peer IP: : {"Code":2,"Msg":"invalid value"}
```

It would have saved a lot of debugging time if the error message said "Unable to autodetect advertiser ip, please set it via --advertise-ip

**Comment by zhaxzhax** [comment]
It's true that Drangonfly miss catching the situation "Unable to autodetect advertiser ip".
I'm gonna fix this.
