### ISSUE TITLE
 Md5 not verified after download

### ISSUE THREAD

**Issue by wuchaojing** [dragonflyoss/Dragonfly#1459]
problem：Md5 not verified after download

the method：
// PostRun
func (cw *ClientWriter) PostRun(ctx context.Context) (err error) {

	src := cw.clientFilePath
	if cw.acrossWrite || !helper.IsP2P(cw.cfg.Pattern) {
		src = cw.cfg.RV.TempTarget
	} else {
		if _, err := os.Stat(cw.clientFilePath); err != nil {
			logrus.Warnf("client file path:%s not found", cw.clientFilePath)
			if e := fileutils.Link(cw.serviceFilePath, cw.clientFilePath); e != nil {
				logrus.Warnln("hard link failed, instead of use copy")
				fileutils.CopyFile(cw.serviceFilePath, cw.clientFilePath)
			}
		}
	}
	if err = downloader.MoveFile(src, cw.cfg.RV.RealTarget, cw.cfg.Md5); err != nil {
		return
	}
	logrus.Infof("download successfully from dragonfly")
	return nil
}

This code：downloader.MoveFile(src, cw.cfg.RV.RealTarget, **cw.cfg.Md5**)
When md5 is not specified in the parameter, cw.cfg.Md5 in this method should be returned by supernode when code=600

advice：
The response returned by the /peer/task interface should be passed to the PostRun method，and then maybe it can：

	// calcute realMd5
        var expectMd5 string
	if p2p.cfg.Md5 != "" {
		expectMd5 = p2p.cfg.Md5
	} else {
		finishData := response.FinishData()
		if finishData != nil {
			expectMd5 = finishData.Md5
		}
	}

	// move file to the target file path.
	if err := downloader.MoveFile(src, p2p.targetFile, expectMd5); err != nil {
		return err
	}

**Comment by jim3ma** [comment]
Yes, the finish data contains md5 info,  we should check the md5 to ensure file is correct.

**Comment by wuchaojing** [comment]
> Yes, the finish data contains md5 info, we should check the md5 to ensure file is correct.

OK，I will submit a PR to fix this problem.
