### ISSUE TITLE
what is the function of MaxBandwidth paramater in supernode

### ISSUE THREAD

**Issue by mchtech** [dragonflyoss/Dragonfly#1477]
## Question
Does it limit the total bandwidth for `back to origin registry` or the total bandwidth for `download from supernode` ?
Does the maxbandwidth parameter of supernode limit the bandwidth of downloading data from the source image warehouse, or does it restrict the bandwidth of other nodes to download data from it?

// supernode的MaxBandwidth参数，是限制从源镜像仓库下载数据的带宽，还是限制其它节点从它下载数据的带宽？

***!!!!WE STRONGLY ENCOURAGE YOU TO DESCRIBE YOUR ISSUE IN ENGLISH!!!!***

**Comment by jim3ma** [comment]
```
back source max bandwidth = max bandwidth - system reserved bandwidth
```

`max bandwidth` and `system reserved bandwidth` can be set in supernode command option.

```
/path/to/supernode --max-bandwidth 1000m --system-bandwidth 100m
```

**Comment by jim3ma** [comment]
BTW, there is no limit by supernode between supernode and dfget, but there is a limit by dfget. 
Please feel free to get description by `dfget --help`.

**Comment by mchtech** [comment]
Will `supernode back to source bandwidth` be limited to 5Mbps, if `max-bandwidth = 1000m` and `system-bandwidth = 995m` on supernode?

**Comment by jim3ma** [comment]
> Will `supernode back to source bandwidth` be limited to 5Mbps, if `max-bandwidth = 1000m` and `system-bandwidth = 995m` on supernode?

Yes, you can have a try.

**Comment by mchtech** [comment]
Thanks, parameters are valid.
