### ISSUE TITLE
Require ARM64 docker images and binaries to add ARM64 job in travis

### ISSUE THREAD

**Issue by odidev** [dragonflyoss/Dragonfly#1486]
Hi,

I am working on adding an ARM64 job in Travis. ARM64 job is failing as docker image **dragonflyoss/nginx:apline** is not available for arm64.

Please check https://travis-ci.org/github/odidev/Dragonfly/jobs/729522338 for the same.
`standard_init_linux.go:211: exec user process caused "exec format error"`

I have built ARM64 binaries as well in ARM64 platform using below steps:

- make build-supernode
- make build-client

```
$ ls bin/linux_arm64/
dfdaemon  dfget  supernode

$ file bin/linux_arm64/*
bin/linux_arm64/dfdaemon:  ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, Go BuildID=siPFbi0V2yoHRNpBwRLL/8WMZ7AX1Wrj00q8trB0H/9PArBl2vblLhnnrx492P/P42fsllta8DvvWF91QuE, not stripped
bin/linux_arm64/dfget:     ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, Go BuildID=hb3d8LxOV-KvorpHfdYY/NoQlyPdkzqkKlTBD93-z/Yz-IEre11oQ46DRFbnJ_/KxUsK3wSOj6y-2PXa1_Y, not stripped
bin/linux_arm64/supernode: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, Go BuildID=hftaDpkvPpAgjtyMljaw/yYqy5u0bD6mWpvkjtYdH/Qr5kyabH72ZD-_cRiU73/JODvczSLvRkVZ4O86EnR, not stripped

```
It will be very helpful if binaries and images are released for ARM64 platform. Please let me know if any help is required from my end. I am very much happy to help.

**Comment by jim3ma** [comment]
Thanks for you work.
For support arm64, We need build dragonflyoss/nginx:apline for multi-arch linke arm64.

**Comment by odidev** [comment]
@jim3ma,

Yes, Maybe we can use **docker buildx** command to build a docker image for arm64, and for releasing arm64 binaries we can add arm64 in goarch in .goreleaser.yml file.

**Comment by jim3ma** [comment]
@odidev I have talked with other members of dragonfly group, they suggest to use `nginx:1.19.2-alpine` image instead of old `dragonflyoss/nginx:apline`. Please have a try.

**Comment by ossdev07** [comment]
@jim3ma,
Thanks for the reply. It works as suggested. Can we have these images uploaded in the docker hub for arm64?

Please let me know if anything can be done from my end.

**Comment by odidev** [comment]
@jim3ma,
Thanks for the reply. It works as suggested. Can we have these images uploaded in the docker hub for arm64?

Please let me know if anything can be done from my end

**Comment by odidev** [comment]
I have updated nginx image in **Dockerfile.supernode** and added ARM64 in goreleaser and Travis files. Please check the commit https://github.com/odidev/Dragonfly/commit/8507b968b8d56f1a94fb6a74c4ca8a08d6ba157d for more details.

For uploading the arm64 docker image we need to update CircleCI publish stage with the usage of docker buildx command.

If interested, I will raise a PR for the same.

**Comment by jim3ma** [comment]
@odidev Thanks. You can create a PR for this.

**Comment by odidev** [comment]
@jim3ma,

I have created a PR as suggested. Please review and let me know if any changes required.
