### ISSUE TITLE
[comments request]  Add comments to the fields of the struct.

### ISSUE THREAD

**Issue by Starnop** [dragonflyoss/Dragonfly#161]
### Ⅰ. Issue Description

> WE ARE LOOKING FORWARD TO ANY PR FROM YOU.

It is warmly welcomed if you have interest to hack on Dragonfly. In my opinion, `struct` in golang is one of the core elements of understanding code, comments of fields are essential. However, we are inadequate in this respect. At the beginning of the project, it was relatively easy to catch up and for further. 

### Ⅱ. Describe what happened

Lack of comments of `struct`.

### Ⅲ. Describe what you expected to happen

Hope the meaning of each field in each `struct`  is clear to make it easier for more contributors to get involved.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- dragonfly version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by allencloud** [comment]
I think this is quite important for an open source project.

**Comment by Starnop** [comment]
Has been done, close it.

**Comment by Starnop** [comment]
For now, our comments are still insufficient, we need to perfect it and develop a good habit of adding comments. So open it again.

**Comment by Starnop** [comment]
It looks like our comments are basically complete. So close it now. 😄
