### ISSUE TITLE
How to download files from another machine in a cluster?

### ISSUE THREAD

**Issue by asadsm** [dragonflyoss/Dragonfly#171]
The example given shows how to download a file with a given URL via the supernode. How would I go about downloading a file which exists on the supernode or any other machine on the network?

**Comment by lowzj** [comment]
We cannot directly download files from machines in dragonfly cluster. 
Files that exist in supernode are encoded by dragonfly, we cannot directly to use them. 
And files on client machines that downloaded by dfget will be copied to `$HOME/.small-dragonfly/data`. These files' copies are using for transforming between `dfget`. They're temporary and will be deleted when no downloading request any more.

**Comment by asadsm** [comment]
Ok so the use case is downloading files from the internet using P2P to speed it up. I for example, cannot use it for internal file sharing which I'm currently doing via rsync.

**Comment by zousheng** [comment]
@lowzj rsync sharing is still a common use case, is it possible or meaningful to add this feature into Dragonfly in the future?

**Comment by lowzj** [comment]
We should discuss this feature and find out which scenarios using `rsync` can be replaced by dragonfly.

**Comment by asadsm** [comment]
To give you a use case:

I have a machine which downloads large data sets. Now this data has to be distributed to various nodes in the cluster. Not all of the data is distributed to all of the nodes.

For example I download huge data sets A, B, C & D.
Node 1 & 3 need A, B & D.
Node 2, & 4 need C & D.
In this case, I'm currently using rsync on each node to get data from the machine which downloaded all the data sets. I'd like to replace this with P2P sharing as there's an overlap of the data required by the different nodes. Obviously this is a very small example of the overall use case. I hope this helps clarify the use-case

**Comment by allencloud** [comment]
First of all, thanks sincerely for constantly using and supporting Dragonfly. We will try our best to keep Dragonfly better, and keep community and eco-system growing. 

To get more feedback of Dragonfly's adoption in industry, would you mind helping comment in issue https://github.com/dragonflyoss/Dragonfly/issues/306 to give more information about your enterprise's Dragonfly usage. Thanks a lot in advance. @asadsm

**Comment by asadsm** [comment]
Sure, will do.
