### ISSUE TITLE
[feature request] support prometheus in supernode to collect metrics

### ISSUE THREAD

**Issue by allencloud** [dragonflyoss/Dragonfly#197]
---
name: Feature Request
about: Suggest your excellent idea for this project
---

## Why you need it?

When we deployed a software, how it runs, what it has done and some other aspects are always important for users. We need to get all these data to have more control the software's runtime, like dragonfly's supernode.

So, I request to support [prometheus](https://github.com/prometheus/prometheus) to collect metrics in supernode of Dragonfly.

## How it could be?

Dragonfly's supernode would expose interfaces for others to collect metrics inside itself. Eventually, all metrics of supernode could be displayed in prometheus's dashboard.

**Comment by yylt** [comment]
supernode directory or src/supernode directory ?
