### ISSUE TITLE
Use an absolute path for DragonFly

### ISSUE THREAD

**Issue by Starnop** [dragonflyoss/Dragonfly#217]
## Question

Now，we use `${HOME}/.dragonfly` and `${HOME}/.small-dragonfly` as the default path which rely on `$HOME`.  However, it willl cause some inconvenience, for example, the  mountPath of Kubernetes should be absolute in generally. 

Maybe an absolute path will be more friendly such as `/etc/dragonfly` and `/etc/small-dragonfly` or something else. WDYT?

**Comment by lowzj** [comment]
IMOP, we should do this.

* `${HOME}/.dragonfly` is the default client's install home. I submit a pull request #213 to change it to `/opt/dragonfly`, and user can config it by using this command:

    ```bash
    ./build/client/configure --prefix={install_home}
    ```

* `${HOME}/.small-dragonfly` stores the client's local log and temporary data. If we change this directory to an absolute path, we should ensure that all users in the host have the right permission to this directory.

**Comment by Starnop** [comment]
> ${HOME}/.small-dragonfly stores the client's local log and temporary data. If we change this directory to an absolute path, we should ensure that all users in the host have the right permission to this directory.

In general, we could use the absolute path like `/var/log` to store the local log or something else. And the premission is permissive for all users. WDYT?

**Comment by lowzj** [comment]
I think it's ok. Maybe we should provide a command line parameter for user to set client's work directory.

**Comment by Starnop** [comment]
Has been implemented. The related PR: #326
