### ISSUE TITLE
Change website URL in project description

### ISSUE THREAD

**Issue by lucperkins** [dragonflyoss/Dragonfly#233]
In the project description, the project website is listed as https://dragonflyoss.github.io/Dragonfly. That link doesn't work. Use https://dragonflyoss.github.io/dragonfly instead (note the lower-case "d").

**Comment by allencloud** [comment]
Thanks  a lot for your advice. Actually this project was named in Dragonfly which is upper-case. 

When doing the migration, we mistook it as a lower-case.

Now I have changed that to be uppercase `Dragonfly`. Does this meet the reqirement? @lucperkins

**Comment by lucperkins** [comment]
@allencloud That link also doesn't work. Actually, it looks like https://d7y.io is the proper link for the project documentation.

**Comment by lowzj** [comment]
Thanks. It's done now.
