### ISSUE TITLE
use dep to do package management

### ISSUE THREAD

**Issue by zhouhaibing089** [dragonflyoss/Dragonfly#246]
---
name: Feature Request
about: Suggest your excellent idea for this project
---

## Why you need it?

[dep](https://github.com/golang/dep) makes it easier to add/update dependencies.

## How it could be?

As far as I can tell, `dep` is so far the most up-to-date supported tool to manage dependencies in go world(`go mod` might be the other choice, but I did not see much adoption yet).  

## Other related information

As the development going, we might have to introduce other dependencies, and this process has to be simple.

**Comment by allencloud** [comment]
Is `dep` the official way of go dependent package management tool? @zhouhaibing089 
Actually govendor is doing well currently in this project.

I would like to hear more reasonable advantages of `dep`.

**Comment by allencloud** [comment]
Could we close this currently? If we have more support to replace that, we keep going? @zhouhaibing089
