### ISSUE TITLE
[feature request] use `spf13/cobra` to refactor dfget/dfdaemon's Command Line part

### ISSUE THREAD

**Issue by allencloud** [dragonflyoss/Dragonfly#249]
## Why you need it?

[spf13/cobra](https://github.com/spf13/cobra) is both a library for creating powerful modern CLI applications as well as a program to generate applications and command files.

We need to use cobra to help construct CLI's flag, subcommand, doc auto-generation and something else.

With cobra, the cli code would be much more clear. And cobra will encapsulate all details about the cli, but provide more concrete and clear programming interface for developers.

Many successful projects are also using it, Kubernetes, etcd, moby, PouchContainer ...

## How it could be?

none

## Other related information

none

**Comment by fengzixu** [comment]
If this issue can be assigned to the developer from the community, I will glad to handle it.

**Comment by Starnop** [comment]
@fengzixu any update? ^_^

**Comment by fengzixu** [comment]
@Starnop  Sorry, there were too heavy works among this period. I will submit a PR within 3 days. :)

**Comment by lowzj** [comment]
Done by pr: https://github.com/dragonflyoss/Dragonfly/pull/257

**Comment by fengzixu** [comment]
Reopen this issue. Because the dfdaemon was not refactored by spf13/cobra. I will finish it as soon as possible.

**Comment by Starnop** [comment]
> Please reopen this issue. Because the dfdaemon was not refactored by spf13/cobra. I will finish it as soon as possible.
> 
> @Starnop @lowzj @allencloud

@fengzixu Thank you for your attention, in fact, I have done it by the way with my next PR, so let me finish it ASAP. Look forward to your comments. Thanks anyway. 😄
