### ISSUE TITLE
Unified development and test environment

### ISSUE THREAD

**Issue by Starnop** [dragonflyoss/Dragonfly#260]
---
name: Feature Request
about: Suggest your excellent idea for this project

---

## Why you need it?

Currently, we run `CI tests` based on the go version of `1.10.4`. However, for contributors, they can only know until have a look at the  `CI script`  or the `CI environment with github`, it's not friendly. So do with the other tools. I did a simple statistic as follows:

Tools:
+ golang : v1.10.4
+ swagger : 0.17.1
+ markdownlint : v0.5.0
+ misspell : latest
+ ShellCheck : latest

Images:
pouchcontainer/pouchlinter:v0.1.2 , the Dockerfile refer to [link](https://github.com/alibaba/pouch/blob/1.0.0.rc2/.circleci/Dockerfile)

So there are two things we should do about it:
1. update the doc of [CONTRIBUTING.md](https://github.com/dragonflyoss/Dragonfly/blob/master/CONTRIBUTING.md) to add version information for related tools for better development and debugging by contributors
2. Use the docker image to build our projrect to avoid strange situations where compiling in the develop environment is fine but not pass the `CI`, more info refer to [link](https://github.com/thockin/go-build-template)

## How it could be?

1. Contributors are well aware of the development and compile environment.
2. Make full use of container technology to unify local development environment and CI environment

## Other related information

 @allencloud  Could you please help provide more information about the image of `pouchcontainer/pouchlinter:v0.1.2`. I think it's better to for contributors to know more about it. THX.

**Comment by fengzixu** [comment]
I would like to handle it. @lowzj @Starnop

**Comment by allencloud** [comment]
>  Could you please help provide more information about the image of pouchcontainer/pouchlinter:v0.1.2. I think it's better to for contributors to know more about it. THX.

@Starnop definitely. I could add more details in repo https://github.com/pouchcontainer/pouchlinter.
