### ISSUE TITLE
镜像强一致性问题

### ISSUE THREAD

**Issue by ordinarymen** [dragonflyoss/Dragonfly#271]
---
name: Question about Dragonfly
about: Ask whatever you want to know or confusion about Dragonfly

---

## Question

1.我从新制作了一个镜像，但是镜像名称别没有改变，超级节点会去验证分片与源镜像一致吗？
2.如果验证源文件变更超级节点会立即拉去新的镜像吗？

**Comment by lowzj** [comment]
超级节点不会主动验证镜像是否变化，会在下一次pull镜像的时候下载新的内容。

镜像下载实际上是对镜像层的下载，每一个镜像层都对应一个blobDigest和相应的url用于下载。镜像内容变化即使镜像名称不变，说明这个镜像的某几个镜像层发生变化，其blobDigest会变，所以对应的url也是发生变化的。

这样在下一次pull镜像的时候，实际上是下载新的镜像层。
