### ISSUE TITLE
supernode 是怎么实现 p2p 的，如何控制 peer 与 peer 之间的访问流程？

### ISSUE THREAD

**Issue by StephenLiuYa** [dragonflyoss/Dragonfly#296]
* 假如有 20 个节点同时去 pull 镜像， 那 supernode 是如何控制这 20 个节点下载镜像的source

**Comment by allencloud** [comment]
![2019-01-03 11 39 22](https://user-images.githubusercontent.com/9465626/50622946-3d300880-0f4c-11e9-91c8-6c67799ed0ea.png)


I uploaded the work way of block distribution. I am wondering if this could answer your question.
