### ISSUE TITLE
[Question] `totallimit` option limits "download + upload" or "download/upload" seprately

### ISSUE THREAD

**Issue by wangyang616** [dragonflyoss/Dragonfly#301]
When I run `dfget` with options `--locallimit 40M --totallimit 40M`, TX and RX both reach 300Mb/s in iftop。The `dfget` version is v0.2.0.
So `totallimit` option limits download and upload seprately?

**Comment by allencloud** [comment]
Thanks for your feedback. @wangyang616 
We will confirm this soon. Actually, could you provide more details about scene?
For example, more specific with your command line command and iftop command and screen result.

**Comment by allencloud** [comment]
This has been placed in FAQ: https://github.com/dragonflyoss/Dragonfly/blob/master/FAQ.md#what-is-the-policy-of-bandwidth-limit-in-peer-network .
PTAL @wangyang616 
I am closing this now, and please feel free to contact us or file another issue if you have any other question.

**Comment by allencloud** [comment]
First of all, thanks sincerely for constantly using and supporting Dragonfly. We will try our best to keep Dragonfly better, and keep community and eco-system growing. 

To get more feedback of Dragonfly's adoption in industry, would you mind helping comment in issue https://github.com/dragonflyoss/Dragonfly/issues/306 to give more information about your enterprise's Dragonfly usage. Thanks a lot in advance. @wangyang616
