### ISSUE TITLE
[feature request] use "spf13/cobra" to auto generate command line markdown document

### ISSUE THREAD

**Issue by allencloud** [dragonflyoss/Dragonfly#306]
## Why you need it?

How to generate user-friendly document is very important work we have to do in Dragonfly project. While I think the best way to make it is to follow the rule **CODE IS DOCUMENT(代码即文档)**. Under such kind of policy, when every update occurs to the CLI-related code, the project has abilities to auto generate the corresponding document. Then the developers can spend less time to construct the document, instead they could have more time to polish the CLI related code when programming which is also reasonable.

We have already supported using `spf13/cobra` to implement COMMAND LINE framework in https://github.com/dragonflyoss/Dragonfly/pull/257. With this work, we can use https://github.com/spf13/cobra/blob/master/doc/md_docs.md to add another command to generate all the CLI document.

After adding the command which is used to generate CLI document, we can make @pouchrobot to automatically generate doc every day when it has update to the cli part. This is quite similar to [PouchContainer](https://github.com/alibaba/pouch).

## How it could be?

use "spf13/cobra" to auto generate command line markdown document

## Other related information

none

**Comment by asadsm** [comment]
We have a cluster of machines and we're using NFS to make sure each machine in the cluster can access data from across the cluster. The problem is that we don't want to overload the network bus so in some cases, it's better to copy over data to local disk from the cluster to avoid network congestion. If DragonFly could provide this functionality, of P2P copy where each machine can act as the source and sink of the data it would be able to provide an excellent alternative to Bittorrent.

**Comment by allencloud** [comment]
Could you move the comment to issue #219 , sorry I mistake the link just now. In addition, could you comment under issue #219, like the following way:

```
Orgnization: Alibaba
Location: Hangzhou, China
Contact: abc@d.com
Scenario: We have a cluster of machines and we're using NFS to make sure each machine in the cluster can access data from across the cluster. The problem is that we don't want to overload the network bus so in some cases, it's better to copy over data to local disk from the cluster to avoid network congestion. If DragonFly could provide this functionality, of P2P copy where each machine can act as the source and sink of the data it would be able to provide an excellent alternative to Bittorrent.
```
