### ISSUE TITLE
super-node sends two requests to file-server , why not once?

### ISSUE THREAD

**Issue by wangchunpeng** [dragonflyoss/Dragonfly#318]
### Ⅰ. Issue Description
10.8.250.205 supernode    
10.8.250.202 Nginx-fileserver  ,filesize= 142703Bytes
10.8.250.201 peer host, from which Dfget is called

### Ⅱ. Describe what happened
when I called Dfget from host 10.8.250.201 , and Nginx recorded  two request logs:

1547113144.623 0.002 :  10.8.250.205 "10.8.250.205" "-" 10.8.250.202 "/10k.txt" GET "-" - "-<||>-" 200 142703 "-" "Java/1.8.0_171" "-<||>-" "-" "-" "-"
1547113144.624 0.000 :  10.8.250.205 "10.8.250.205" "-" 10.8.250.202 "/10k.txt" GET "-" - "-<||>-" 304 0 "-" "Java/1.8.0_171" "-<||>-" "-" "-" "-"

### Ⅲ. Describe what you expected to happen
only one request log is expected

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.dfget --node 10.8.250.205 -u "http://10.8.250.202:2222/10k.txt" -o /tmp/in.html
2.
3.

### Ⅵ. Environment:
nginx config:
 1 server {
  2     listen 2222;
  3     charset utf-8;
  4     location /{
  5         default_type  'application/octet-stream';
  6         add_header "Access-Control-Max-Age" 1728000;
  7         root /home/test;
  8     }
  9 }
 10

- dragonfly version:
- OS (e.g. from /etc/os-release): Unbuntu
- Kernel (e.g. `uname -a`):Linux test-cdn-chengdu-office2 3.10.101-cdn
- Install tools: 
- Others:

**Comment by lowzj** [comment]
1. get file length from source server
2. download the file from source server
