### ISSUE TITLE
Dragonfly dfget 数据流

### ISSUE THREAD

**Issue by sunny821** [dragonflyoss/Dragonfly#327]
---
dfget 拉取piece后写文件的数据流转

---
代码：Dragonfly-master
背景：本地安装完Dragonfly,通过docker pull对比拉取Harbor和Dragonfly的效率，Dragonfly拉取过程有多次文件写入，本地网络带宽万兆情况下，大批量的磁盘IO可能影响整体性能；带着疑问对比代码处理过程

疑问点：
1.函数：NewTargetWriter(watch targetQueue)写入的TempTarget($workhome/dfdaemon/data/dfget-pid-time.tmp)路径有相关业务逻辑应用吗
2.power_client.go中
![dragonfly-1](https://user-images.githubusercontent.com/16682993/51223942-dd3f5600-197e-11e9-90d9-f73b5938766d.png)
做了两次硬链接，其中clientFilePath到TempTarget的链接做什么用的
3.在什么场景下才能用到标红的这个逻辑
![dragonfly-2](https://user-images.githubusercontent.com/16682993/51224326-483d5c80-1980-11e9-8350-16a8c6c42dd3.png)

谢谢

**Comment by lowzj** [comment]
因为蜻蜓文件下载是p2p模式，在本地需要有一个临时文件目录`$HOME/.small-dragonfly/data`，用于临时存储已下载的文件并提供给其他peer节点下载。硬连接的特性是虽然文件名不同，但是指向的inode和数据都是同一份，即使删除一个文件，也不会影响实际的数据，可以减少写次数；但是有个限制是跨文件系统不能使用硬连接。

---

> 1.函数：NewTargetWriter(watch targetQueue)写入的TempTarget($workhome/dfdaemon/data/dfget-pid-time.tmp)路径有相关业务逻辑应用吗
> 2.做了两次硬链接，其中clientFilePath到TempTarget的链接做什么用的

这个硬连接主要用于判断目标目录和蜻蜓的缓存目录是否在同一个文件系统里，如果是的话，`TempTarget`是没有用的，也不会往这里写数据。如果不是的，即跨文件系统的情况下，会写`TempTarget`。

> 3.在什么场景下才能用到标红的这个逻辑

跨文件系统的情况，会用到这里的逻辑，因为`TempTarget`和`targetFile`是同一个目录下，实际是一个rename操作，尽量减少写盘次数。

**Comment by sunny821** [comment]
好的，了解，谢谢

**Comment by Starnop** [comment]
The question has been answered, close it now.
