### ISSUE TITLE
[feature request] refactor the makefile of Dragonfly

### ISSUE THREAD

**Issue by fengzixu** [dragonflyoss/Dragonfly#330]
---
name: Feature Request
about: Suggest your excellent idea for this project

---

### short

Targets in the makefile file are not friendly and simple. We should refactor it so that users can use it efficiently.

### long

In the previous time, I refactored the makefile of the Dragonfly. The biggest change is using docker to build binary files(Eg. dfget, dfdaemon): https://github.com/dragonflyoss/Dragonfly/pull/276. But it is not perfect and friendly. When @allencloud  want to add the tool of generating docs of client(Eg. dfget, daemon), he found that we don't have any command to build client binary files in the local environment other than the container. So I add the target called `build-client-local` : https://github.com/dragonflyoss/Dragonfly/pull/316 . 

After that I discussed with @allencloud  about `makefile` file, we considered that we should simplify the`makefile` file, so that it is friendly to users.

## How it could be?

I considered two principles:

#### The content of `makefile` is universal and simple. 

* make build: Using local environment other than docker to build all components, such as dfget, dfdaemon. 
* make install: Using local environment other than docker to build and install all components in the specified path.
* make check：Using go tools(Eg. gofmt, golint..) to check whether there are some non-standard codes.
* make test:  Using local environment other than docker to run unit test of Dragonfly.
* make clean: clearing binary files if you have run the `make build` or `make install` command

#### Retaining the command that uses Docker tech.

The reason I insist on proposing this point is that using docker tech to build components can help developers to reduce difficulties about develop environment, such as go version, docker version and so on. But I don't add them to the`makefile`. They will be stored in the dir : `$GOPATH/src/github.com/dragonflyoss/Dragongfly/hack`

**Comment by lowzj** [comment]
It's convenient for me to build dragonfly client's binary files by using docker these days. IMOP, we should retain this building way.

And could we add an env variable to Makefile, such as:

```sh
# use local environment
make build
# use docker way
make USE_DOCKER=1 build
```

The default way is using local environment, if we set `USE_DOCKER`, then use docker way to build.
