### ISSUE TITLE
The first open source weekly meeting of Dragonfly

### ISSUE THREAD

**Issue by Starnop** [dragonflyoss/Dragonfly#349]
Thanks to your attention and support for the Dragonfly project. Dragonfly is currently in the `sandbox` stage as a new project of the CNCF. In order to create a thriving community environment, and be close with developers/end-users, the first open source weekly meeting of Dragonfly will be organized tonight. We are looking forward to your participation. The following are the relevant content of the meeting:

Meeting Time：
Time: Jan 24 2019 8PM GMT+8 (Beijing Time)

Meeting Address（online）：
Zoom：  https://zoom.us/j/3106836401 

Meeting Organizer: Dragonfly Community

Agenda:
+ Dragonfly&Community Introduction （5min）
+ Community Ice Breaking
  + Adopters Introduction (5min)
  + Developer’s voice (5min)
+ Roadmap Introduction  (8min)
+ Help needed from community (8min)
+ Open Q&A (10min)

If you have any questions, feel free to leave a comment here.  See you tonight. 😄

**Comment by zhouhaibing089** [comment]
Not sure whether we have a mailing list, if we do not, we probably should setup one.

We probably should send invites to each of member as well.
