### ISSUE TITLE
Plan of Dragonfly Testing

### ISSUE THREAD

**Issue by lowzj** [dragonflyoss/Dragonfly#352]
# Background

This is one part of [Golang Refactoring Plan of the Whole Dragonfly Project](https://github.com/dragonflyoss/Dragonfly/issues/346).

Quality is also taken serious when refactoring Dragonfly. And it is one kind of continuous work which needs persistence. We wish to cover as much as possible on test to guarantee the quality of dragonfly.

# Details

Actually we wish to set up the essential test for dragonfly on several parts:

* Unit test;
* API integration test;
* CLI integration test;
* node end-to-end test;

## Test Guide

- [ ] complete the document of test guide

## Unit Test

- [x] unit test of `supernode`
- [x] unit test of `dfdaemon`
- [x] unit test of `dfget`
    - [x] unit test of module `uploader`. pr: #402 #401 
    - [x] unit test of module `downloader`
    - [x] unit test of module `api`

## Integration Test

In integration test, we will take the following testing architecture to cover test dimensions.

<img width="993" alt="2019-02-01 10 59 33" src="https://user-images.githubusercontent.com/9465626/52100502-be91be00-2612-11e9-9462-f8e28028dd6a.png">

We will deploy a travis CI VM and deploy three containers in the VM with docker:

* one container for supernode;
* two containers for dfget (currently we only test dfget for file, dfdaemon not included)

Then we use test cases to cover supernode and dfget.

- [x] testing of downloading files.
- [x] testing of pull images.

##

**Comment by Starnop** [comment]
I will finish the `unit test of module downloader` ASAP.

**Comment by lowzj** [comment]
I will finish the `unit test of module uploader`
