### ISSUE TITLE
[feature request] add target `docs` in Makefile to generate API&CLI document

### ISSUE THREAD

**Issue by allencloud** [dragonflyoss/Dragonfly#375]
## Why you need it?

Currently, dragonfly has supported swagger and cobra, and then we can easily use swagger.yml and cobra to generate the corresponding docs:

**API docs**

* swagger;
* target file: https://github.com/dragonflyoss/Dragonfly/blob/master/apis/swagger.yml
* doc destination path: https://github.com/dragonflyoss/Dragonfly/blob/master/docs/api_reference/apis.md

**CLI doc**

* [cobra](https://github.com/spf13/cobra/)
* target file: https://github.com/dragonflyoss/Dragonfly/tree/master/docs/cli_reference
* how to generate them: `dfget gen-doc -p path`;  `dfdaemon gen-doc -p path` after `make build`

It would be quite easy for us to generate and update docs via robot.

Could you help on this? @fengzixu

**Comment by allencloud** [comment]
Any update on this? Without this, the @pouchrobot will generate documents in a wrong way and also in a non-general way. @fengzixu

**Comment by fengzixu** [comment]
@allencloud 😆 Too happy and relax during the spring festival. I will resolve it within this week. Is it ok?

**Comment by allencloud** [comment]
OK 😺
