### ISSUE TITLE
[feature request] dfdaemon support forwarding requests of some trusted hosts

### ISSUE THREAD

**Issue by godliness** [dragonflyoss/Dragonfly#385]
---
name: Feature Request
about: Suggest your excellent idea for this project

---

## Why you need it?

If we only use `registry-mirrors ` to support request forwarding, then all the yaml of running pods need change their image field. eg: from repo.image.local/test:0.0.1 to 127.0.0.1:65001/test:0.0.1 that is not be accepted for platform users; so we try to use `http_proxy` in docker.service file directly, but there is still some problems that we only support "127.0.0.1" and "localhost" and "hostIP" that dfdaemon running on.

## How it could be?

What about we support multi trusted hosts which could be passed by command line params which could be named "trust-hosts" or something else?

## Other related information

Related to issue: 

https://github.com/dragonflyoss/Dragonfly/issues/264

https://github.com/dragonflyoss/Dragonfly/issues/289

Referenced:

https://www.bladewan.com/2018/08/18/docker_image_p2p/
![image](https://user-images.githubusercontent.com/10972761/52609090-0e943e80-2eb7-11e9-8ef5-4dfe6096a869.png)

Any suggestions？

/cc @allencloud 
/cc @lowzj

**Comment by lowzj** [comment]
closed because that pr: #389 is merged
