### ISSUE TITLE
Dfget is much slower than WGet

### ISSUE THREAD

**Issue by mdchao2010** [dragonflyoss/Dragonfly#409]
The web file server built locally tries to download WGet and dfget several times, and dfget is much slower each time. For 500 m files, dfget takes 34 seconds and WGet takes 7 seconds. But when downloading files on the Internet, dfget has a lot of advantages. Has anyone ever encountered it?

// 自己本地搭建的web文件服务器，尝试wget和dfget多次下载，dfget每次都会慢很多。500m的文件，dfget耗时34s，wget耗时7s。但是在网络上下载文件，dfget很有优势，有谁遇到过么？ 

dfget 0.0.1，supernode 0.2.0.
```
[root@java5 test]# time dfget -u 'http://192.168.192.102:8888/download/harbor.tgz' -o /tmp/test/harbor1.tgz --node "192.168.192.101"
--2019-02-20 17:51:03--  http://192.168.192.102:8888/download/harbor.tgz
current user[root] output path[/tmp/test/harbor1.tgz]
/opt/df-client/vendor/requests-2.18.4-py2.7.egg/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.22) or chardet (2.2.1) doesn't match a supported version!
  RequestsDependencyWarning)
dfget version:0.0.1
workspace:/root/.small-dragonfly/ sign:110546-1550713864.234
client:192.168.192.105 connected to node:192.168.192.101
init success...
start download by dragonfly
download SUCCESS(0) cost(33.691s) length:597857483 reason:0
real    0m34.378s
user    0m5.688s
sys     0m6.931s
```
```
[root@java5 test]# time wget -q http://192.168.192.102:8888/download/harbor.tgz
real    0m6.908s
user    0m0.068s
sys     0m2.201s
```

***!!!!WE STRONGLY ENCOURAGE YOU TO DESCRIBE YOUR ISSUE IN ENGLISH!!!!***

**Comment by lowzj** [comment]
The default downloading speed of `dfget` is 20Mb/s, please set option: `--locallimit` to change it.

**Comment by Starnop** [comment]
@mdchao2010  Have you tried more? And what is the result now?

**Comment by lowzj** [comment]
closed because of no feedback, please reopen it if you get any new problem.

**Comment by mdchao2010** [comment]
@lowzj @Starnop thanks it`s ok. Sorry, forget the feedback.
