### ISSUE TITLE
[feature request]an area aware schedule policy to dragonfly.

### ISSUE THREAD

**Issue by xq2248** [dragonflyoss/Dragonfly#428]
name: Feature Request
about: Suggest your excellent idea for this project

In networks with large cross, the network are divided into different areas. Supernode is depolyed in the root node ,  the dfget clients are deployed in different area. All dfget Clients can download files from supernode with pattern cdn. But a dfget client can only download file pieces from other peers within the same area, also it can only serve pieces download requests to the peers within the same area.

I suggest:
Dfget command add a new optional flag "-a xxx"(for short) or "--area=xxx", to sepcify the area of the peer. When dfget send peer regist request to the supernode, supernode store the area property of the peer. Thus supernode can know the area of all the peers. When dfget send pull piece request to the supernode, supernode only returns the peers within the same area, or return peers within the same  area priority to peer within different area.

**Comment by xq2248** [comment]
英语比较差，用中文描述以下。
在跨度很大的网络中，supernode可能部署在网络中心，supernode可以给所有区域中的peer提供CDN下载服务。而dfget peer所在的网络存在两种可能：
A dfget peer可能部署在网络隔离的不同区域，一个区域内的peer之间可以相互对等传输，而不同区域可能网络无法联通，导致无法跨区域对等传输。这个时候supernode应该只返回同一区域的peers来提供P2P下载服务。
B 有的时候，即便不同区域的peer网络能够相通，但是同一个区域之间的peers P2P对传是最快的。这个时候supernode应该优先返回同一区域内的peers来提供P2P下载服务，其次才是其他区域的peers。

实现：
dfget命令增加一个可选的参数 -a xxx 或者--area=xxx。
dfget peer向supernode发送peer regist请求时，携带这个peer的area位置参数。
supernode记录peer的area。
对于场景A，supernode只返回同一区域的peers信息。
对于场景B，supernode优先返回同一区域的peers信息，只有同一区域没有可以提供服务的peer时，才返回其他区域的peers信息。

**Comment by allencloud** [comment]
Thanks for your feature request. For a straightforward understanding of your proposal, I think what you request is totally reasonable. It is an extension of scheduler and it takes the network reality into consideration.  
Would you first give some input on this topic? @lowzj @Starnop @garfield009 
And in addition, maybe we can review this in our community meeting.

**Comment by lowzj** [comment]
That's a good feature to improve Dragonfly to distribute data in p2p network. We should consider how to make it easier and more extensible for users and developers to implement new scheduling algorithms and add new factors participating in peer scheduling.

Currently, there's a workaround to solve part of your request:  **set different values to option `--identifier` of `dfget` in different areas**. 
This makes Dragonfly to construct different p2p networks in different areas. Peers between different areas will not transfer data to each other. But the side-effect is that `Supernode` will download the source file more than once(it's the number of areas).

**Comment by xq2248** [comment]
@lowzj @jim3ma 

> Currently, there's a workaround to solve part of your request: **set different values to option `--identifier` of `dfget` in different areas**.
> This makes Dragonfly to construct different p2p networks in different areas. Peers between different areas will not transfer data to each other. But the side-effect is that `Supernode` will download the source file more than once(it's the number of areas).

> Currently, there's a workaround to solve part of your request: **set different values to option `--identifier` of `dfget` in different areas**.
> This makes Dragonfly to construct different p2p networks in different areas. Peers between different areas will not transfer data to each other. But the side-effect is that `Supernode` will download the source file more than once(it's the number of areas).

Test Case: three peers download 10-1.zip with p2p.
Three peers, Peer1 and Peer2 are in the region region001.  Peer3 is in region region002.

Peer1 at region001 triggle first downloading at region001, 
Peer2 at region001, download file from Peer1
Peer3 at region002, download file from SuperNode.

it works, and supernode only download the file once from source.

**Comment by flystarts** [comment]
How's this feature going?  I see the  PR 1397 is not merged yet

**Comment by xq2248** [comment]
I saw this feature in DragonFly2. There will be a better implemention.

**Comment by xq2248** [comment]
There will be a better implemention in DragonFly2

**Comment by flystarts** [comment]
good news! but where is the DragonFly2

**Comment by jim3ma** [comment]
DragonFly2 is under development. The repo will be public recently.
