### ISSUE TITLE
[bug] The install_server.md has error.

### ISSUE THREAD

**Issue by BonnieTang** [dragonflyoss/Dragonfly#447]
### Ⅰ. Issue Description
When I first deployed the server according to the  instrction #Procedure - When Deploying with Docker#. 
I found it must be  compiled the source code before  #2.build-supernode# .
https://github.com/dragonflyoss/Dragonfly/edit/master/docs/user_guide/install_server.md
### Ⅱ. Describe what happened
first step : 
```
git clone https://github.com/dragonflyoss/Dragonfly.git
```
then:
``` cd Dragonfly```
now:
```
$ make build-supernode
Begin to build supernode.
./hack/build-supernode.sh 
Begin to build supernode in the local environment.
/ hack/build-supernode.sh: Line 19: mvn: No command found

// ./hack/build-supernode.sh:行19: mvn: 未找到命令 

Cp: Cannot get the file status of "/app/dragonfly/Dragonfly/hack/. / src/supernode/target/supernode.jar" (stat): No file or directory

// cp: 无法获取"/app/dragonfly/Dragonfly/hack/../src/supernode/target/supernode.jar" 的文件状态(stat): 没有那个文件或目录 

BUILD: supernode in /app/dragonfly/Dragonfly/bin/supernode.jar
```
### Ⅲ. Describe what you expected to happen
BUILD success.
### Ⅳ. How to reproduce it (as minimally and precisely as possible)
The description document needs to be supplemented with this content:
```
2.Enter the project directory.
cd Dragonfly/src/supernode
2.Compile the source code.
mvn clean -U install -DskipTests=true
```
then
```
4.Build the Docker image. 
build-supernode
```
### Ⅴ. Anything else we need to know?
no
### Ⅵ. Environment:
- dragonfly version: master
- OS (e.g. from /etc/os-release): CentOS Linux release 7.6.1810 (Core) 
- Kernel (e.g. `uname -a`):4.4.47
- Install tools: docker 18.09.2 
- Others:

***!!!!WE STRONGLY ENCOURAGE YOU TO DESCRIBE YOUR ISSUE IN ENGLISH!!!!***

**Comment by Starnop** [comment]
The doc has been updated and you can check it here  https://d7y.io/zh-cn/docs/userguide/install_server.html. So close it now.
