### ISSUE TITLE
proxy模式下https registry无法pull镜像

### ISSUE THREAD

**Issue by lazybetrayer** [dragonflyoss/Dragonfly#449]
### Ⅰ. Issue Description
Setting HTTP_PROXY, the HTTPS request will also pass through proxy, so a CONNECT request will be sent to dfdaemon, which returns 404. As for registry and auth service domain names, they can't be used without NO_PROXY filtering.

// 设置HTTP_PROXY，https请求也会经过proxy，所以会向dfdaemon发送CONNECT请求，dfdaemon返回了404。对于registry和auth服务域名一样，没有办法通过NO_PROXY过滤的情况就不能用了。 

### Ⅱ. Describe what happened
![image](https://user-images.githubusercontent.com/4188244/54405208-cc0d8e00-4710-11e9-800c-ac77cdf34479.png)
![image](https://user-images.githubusercontent.com/4188244/54405133-91a3f100-4710-11e9-9e3a-650be63fd7cf.png)

***!!!!WE STRONGLY ENCOURAGE YOU TO DESCRIBE YOUR ISSUE IN ENGLISH!!!!***

**Comment by xh4n3** [comment]
You can set a HTTPS_PROXY for docker, and forward the https traffic to another tcp proxy, like squid.

**Comment by lowzj** [comment]
see #525
