### ISSUE TITLE
Unable to download files in blocks

### ISSUE THREAD

**Issue by yinxianliang** [dragonflyoss/Dragonfly#467]
---
name: Question about Dragonfly
about: Ask whatever you want to know or confusion about Dragonfly
---
## Question

Client, when downloading the file, a warning appears: WARNING has not available pieceTask, maybe be be resource lack. Does that mean you can't download files in blocks? What are the possible causes? Thank you

// 客户端，下载文件时，出现警告：WARNING has not available pieceTask,maybe resource lack。是不是意味着不能分块下载文件？可能造成的原因是什么？谢谢

***!!!!WE STRONGLY ENCOURAGE YOU TO DESCRIBE YOUR ISSUE IN ENGLISH!!!!***

**Comment by lowzj** [comment]
It's not an error and there is no effect on p2p downloading. It just tells you that there is no prepared piece to download or the piece is already downloaded by dfget.

**Comment by yinxianliang** [comment]
谢谢

**Comment by allencloud** [comment]
Can we add this issue as a question and answer into [FAQ](https://github.com/dragonflyoss/Dragonfly/blob/master/FAQ.md)?

I think in the future there will be other users who meet this issue, and we can give this reference in FAQ to them?

Could you help to make it?  @yinxianliang

**Comment by yinxianliang** [comment]
@allencloud 好的，有时间我整理一下
