### ISSUE TITLE
[feature request]add proxy for supernode

### ISSUE THREAD

**Issue by ansinlee** [dragonflyoss/Dragonfly#472]
it is very slow to visit out net from inner china without proxy, 
can we add a proxy to supernode?

add SuperNode Properties like:
  supernode.proxy=http://ip:port
  supernode.proxyRule=hub.docker.com,*.google.com

**Comment by Starnop** [comment]
I think it might be more appropriate to use an external proxy, such as nginx. WDYT?

**Comment by Starnop** [comment]
And I will close this issue now. Please open it again and add your comments here if you have any questions.
