### ISSUE TITLE
Why does Dragonfly can not support HTTPS mirror repositories well？

### ISSUE THREAD

**Issue by Starnop** [dragonflyoss/Dragonfly#525]
# Why does Dragonfly can not support HTTPS mirror repositories well？

Dragonfly is an open source intelligent P2P based image and file distribution system. Its goal is to tackle all distribution problems in cloud native scenarios. However, Dragonfly does not support HTTPS private repositories well currently.

Before explaining this problem, let's take a look at the what will happen when you perform `docker pull ...`, which can be summarized as the following two steps: 

+ Send a request `GET /v2/<name>/manifests/<reference>` to get the image manifest file
+ Send a request `GET /v2/<name>/blobs/<digest>` to get the image layer files

NOTE: We only consider network-related steps here .

Currently Docker provides some hack points for Dragonfly or other proxy servers. 

+ registry-mirror
+ http proxy
+ https proxy

## registry-mirror

In fact, the `registry mirror` is just a local cache for a remote image registry. In this way, the `registry mirror` will get the image from remote repository  and cache it locally if the image does not exist locally. Please check out the [Docker documentation](https://docs.docker.com/registry/recipes/mirror/) for more details.

If the registry mirror is configured as `the address of dfdaemon proxy`, and then the request initiated by docker daemon will be sent to the Dragonfly. And then Dragonfly will download images via P2P.

It seems that everything is wonderful, but there are a few issues should be noticed:

+ [It’s currently not possible to mirror another private registry. Only the central Hub can be mirrored.](https://docs.docker.com/registry/recipes/mirror/#gotcha)  What does that mean?  The Docker daemon will forward the image download request to the configured registry mirror when you  use `docker pull busybox:latest` or docker pull `dockerhub.domain/library/busybox:latest`. However, the images will be downloaded from the original address directly without going through the registry mirror when you use `quay.io`, `gcr.io`  and your private image registry domain name. Therefore, you can only download your images in the same way as downloading the official image and configure some rules for Dragonfly.

+ Multi-registries configuration is not supported. Docker daemon will construct the request with `registry-mirror-host`(usually http://127.0.0.1:65001 for Dragonfly)`. So dfdaemon will always receive a request with request.Host `127.0.0.1`, and only one rule will be matched, of course.

![image](https://user-images.githubusercontent.com/31209634/57517871-586fb200-734a-11e9-9164-ebcbc8598cff.png)

### solution?

In fact, the issue of that registry-mirror only supporting Docker's official Hub image registry has been paid attention many years ago, and there are many discussions in the community. And there are some pull requests have also been submitted. Maybe you are interested to pay attention the PR [Implement private registry mirror support](https://github.com/moby/moby/pull/34319) submitted by @vrothberg, but this PR has been opened for two years, and the author has changed employer and her former colleagues who will kick the PR over the finish line. The above problems will be solved if this PR be merged.

You can find more information at the following links:
+ Master issue: private registry caching https://github.com/docker/distribution/issues/1431
+ Enable engine to mirror private registry https://github.com/moby/moby/issues/18818
+ Pull Through Cache For Private Registry https://github.com/docker/distribution/issues/922

## http proxy

In this way, all http requests sent by the Docker daemon will be forwarded to the proxy and handled by the proxy. So you can use `docker pull private-mirror-registry/refs` to pull images from your private registry. And the Dragonfly can be configured with multiple registries. Maybe this time you will regard the config of "insecure-registries" is a good solution. If we configure Dragonfly as the http_proxy of Docker daemon and then the Dragonfly parses the received http request and downloads the images via HTTPS. Perfect ! Let's do it. 
But unfortunately, you will find that the download request has not been sent to the http proxy(Dragonfly). Why? Let's take a hard look at the [document](https://docs.docker.com/registry/insecure/#deploy-a-plain-http-registry). 
Then you will get the answer from the following paragraph:

> With insecure registries enabled, Docker goes through the following steps:

>+ First, try using HTTPS.
>    + If HTTPS is available but the certificate is invalid, ignore the error about the certificate.
>    + If HTTPS is not available, fall back to HTTP.

![image](https://user-images.githubusercontent.com/31209634/57517986-9e2c7a80-734a-11e9-9f38-7c230f26a47d.png)

### solution?

+ The easiest and most rude way is to modify the Docker source to make it does not enforce HTTPS attempts.

+ Modify the private image registry. Do not listen for HTTPS requests on the default 443 port so that the Docker will send http requests after failing to try with HTTPS.
+ Modify the private image registry. Use HTTP for the image layer files and use HTTPS for the others.

Of course, the above methods are quite invasive.

### https proxy

The https proxy is a transparent mechanism essentially, and the proxy can't parse the request content. Therefore, if Dragonfly is configured as an HTTPS proxy, the powerful role of Dragonfly's P2P will be useless.

![image](https://user-images.githubusercontent.com/31209634/57518793-763e1680-734c-11e9-9c31-98d44128df9c.png)

### solution?

There is not a good way yet. If you have any good ideas, welcome to commit.
And @inoc603 has submitted a pull request #523. 

## docker pull dfdaemon/...

Of course, we can not only find a way to hijack the download request through some way provided by the Docker daemon, but also use the Dragonfly as the registry of `docker pull` directly. However, this method requires you to pull images use the format like `docker pull 127.0.0.1: 65001 / ref`, which is not very friendly.

**Comment by Starnop** [comment]
@inoc603 
Thanks for your advice https://github.com/dragonflyoss/Dragonfly/pull/501#discussion_r282365350. And could you please submit your comments here?

**Comment by Starnop** [comment]
In fact, Maybe it's not a bad idea to replace the docker with contained. 😄 

 And you can [configure the your private image registry for containerd for use with the cri plugin](https://github.com/containerd/cri/blob/master/docs/registry.md)

**Comment by Starnop** [comment]
# 为什么 Dragonfly 不能很好的支持 HTTPS 镜像仓库

Dragonfly 为Docker 镜像分发提供P2P 分发，但是在HTTPS 仓库的支持却一直并不完美。

在解释这个问题之前，我们先来了解一下 [Docker 的下载流程](https://docs.docker.com/registry/spec/api/#pulling-an-image)，可以总结为如下两个步骤：（这里抛开除网络下载的其他步骤，如验证，合并镜像层，解压缩等操作不谈）

- 发送请求 `GET /v2/<name>/manifests/<reference>` ，获取镜像的 mainfest 文件
- 发送请求 `GET /v2/<name>/blobs/<digest>` ，获取镜像层文件

Dragonfly 想要代理Docker 的镜像下载，便需要hack 这两个网络连接。目前 Docker 提供以下几种方式可以作为Dragonfly 或者其他代理组件的切入点。

- registry-mirror
- http proxy
- https proxy

## registry-mirror

严格来说，这种方式**并不是一种代理**，而是作为远程镜像仓库的本地缓存仓库。这种模式下，如果registry mirror 中不存在，则回源去远程仓库拉取镜像，并在registry mirror 做缓存。更多细节，可以查看[Docker 文档](https://docs.docker.com/registry/recipes/mirror/)。

如果将registry mirror 配置为Dragonfly 的dfdaemon 代理地址，Docker daemon 发起的请求便都会先经过Dragonfly 系统，只有在Dragonfly 无法返回正确的结果时，才会回源去远程仓库下载。

看起来一切很合理，但是需要注意几个问题：

- Registry mirror 目前[只支持 Docker Hub 的mirror](https://docs.docker.com/registry/recipes/mirror/#gotcha)。这意味着什么呢？当你使用 `docker pull busybox:latest` 或者 `docker pull dockerhub.domain/library/busybox:latest` 的时候Docker daemon 才会将镜像下载请求转发至配置的 `registry mirror` 项，而对于 `quay.io` , `gcr.io` 等以及你的私有镜像仓库域名，都会直接去原地址下载，而不经过 `registry mirror` 。因此，**如果要使用Dragonfly 代理私有镜像仓库，只能通过 `docker pull busybox:latest` 这样的方式，配合Dragonfly 的 registry 配置进行下载。**
- 不支持多仓库地址配置，Docker daemon 需要将registry-mirror 参数配置为dfdaemon 的地址(通常为http://127.0.0.1:65001 )，并将请求转发。那么对于dfdaemon 来说，便只会收到一种请求，因此也就只能匹配一条规则。

### 是否有解？

实际上，对于 Registry mirror 只支持 Docker 官方 Hub 镜像仓库的问题在很多年前就已经被关注了，社区也有很多的讨论，PR 也提交了好几个。目前最有希望合并的PR就是 [@vrothberg ]() 提交的PR  [Implement private registry mirror support](https://github.com/moby/moby/pull/34319)，不过这个PR 已经 open 两年了，提交的作者也从原公司离职，将这个PR转交给了其他人来推。如果该PR 合并，那么我们上述的问题也就能够迎刃而解了。

关于该问题社区主要讨论的几个issue地址，感兴趣的同学可以了解一下：

- Master issue: private registry caching [https://github.com/docker/distribution/issues/1431](https://github.com/docker/distribution/issues/1431)
- Enable engine to mirror private registry [https://github.com/moby/moby/issues/18818](https://github.com/moby/moby/issues/18818)
- Pull Through Cache For Private Registry [https://github.com/docker/distribution/issues/922](https://github.com/docker/distribution/issues/922)

## http proxy

这种方式需要你的私有镜像仓库为非https 仓库，并将该仓库地址[配置为Docker daemon 的 insecure-registries](https://docs.docker.com/registry/insecure/)。使用该方式，Docker daemon 发送的所有 http 请求都会经过代理，由代理来处理，因此，用户可以通过 `docker pull 私有镜像仓库/镜像名`  的方式进行拉取。并且可以为 Dragonfly dfdaemon 配多个镜像仓库代理项，根据域名代理不同的镜像仓库。

这种方式看起来很nice，但是同样有一些问题我们需要解决：

- 你的镜像仓库必须是非HTTPS 仓库。这又是为什么呢？看似 Docker 为我们提供了 `insecure-registries` 的配置项，只要将私有镜像仓库配置为 `insecure-registries` ；理所当然的Docker daemon 就会发送HTTP 请求给http proxy(也就是我们的Dragonfly),后面的事便交给Dragonfly 去做就好了。但是Docker daemon 并不这么做，即使你配置了 `insecure-registries` , so what? **Docker daemon 仍然会先去试一试 HTTPS 请求**，如果通了，所有的流量便以 HTTPS 的方式进行传输，http proxy 的配置便毫无作用。

可以通过[官方文档](https://docs.docker.com/registry/insecure/#deploy-a-plain-http-registry)查看更多信息：

### 是否有解？

- 最简单粗暴的方式，改 Docker 源码，不强制执行 HTTPS 尝试。
- 对私有镜像仓库作出改造，HTTPS 端口不是监听在默认443 端口，这样Docker 在HTTPS 请求发送不成功后，便会转为http 请求，然后通过dfdaemon 代理向指定的端口发送HTTPS 请求。
- 对私有镜像仓库作出改造，在获取镜像层文件的其他请求中使用HTTPS 请求，而下载镜像层文件则使用HTTP请求，这样下载镜像层流量同样会由dfdaemon 代理。

当然，上述的方式都相当具有侵入性。

## https proxy

https proxy本质上是一种透传机制，而传输的内容代理无法作出解析，因此，如果将 Dragonfly 配置为HTTPS 代理，那么Dragonfly 的P2P 的强大作用也就无用武之地了。


### 是否有解？

除了Dragonfly 拦截流量自制 CA，暂时没找到一种好的方式，如果你有什么好的想法，欢迎commit。

## Docker pull dfdaemon/...

当然，我们不仅仅可以想办法通过Docker daemon 提供的某种方式拦截下载请求，也可以直接将docker daemon 作为 docker pull 的镜像仓库地址。不过这种方式就需要用户通过 `docker pull dfdaemonip:65001/镜像名`  的方式来拉取，而不能通过原有镜像仓库名的方式，这样对于用户的体验并不十分友好。

社区中有一篇介绍使用该方式来下载HTTPS 镜像仓库的博客，有兴趣尝试的可以[参考链接](https://d7y.io/zh-cn/blog/d7y-private-registry.html)。

**Comment by inoc603** [comment]
I think using http_proxy is the least invasive way to support https registries as of now. Users don't have to modify and ship docker or change their registries.

For dfdaemon's http proxy, https requests can be handled in three ways:
- tunnel requests directly: safe, but can't leverage dragonfly's distribution ability
- use self-signed certificates: have to manually set `insecure-registries` in `/etc/docker/daemon.json`, and users have accurate control
- use local CA: powerful, all connection are made "safe" by force, but may have unknown security issues

Tunneling requests are already supported in dfdaemon in #486 . Using self-signed certificates is being working on in #523 .
