### ISSUE TITLE
[feature request][SoC2019] support prometheus in Dragonfly

### ISSUE THREAD

**Issue by allencloud** [dragonflyoss/Dragonfly#526]
## Why you need it?

[Prometheus](https://prometheus.io/) has been very popular in the container ecosystem. And it is also a project in cncf, graduated. We have a feature request to support Prometheus in native Dragonfly.

## How it could be?

1. We wish to support Prometheus metric in both dfdaemon and supernode. 
2. dfdaemon and supernode should expose metrics API for prometheus. 
3. At the runtime, we should show metric status of Dragonfly when using some display tools, like [grafana](https://grafana.com/).

## Other related information

I think we should define the metrics first, and kick the ball.
For the metric definition, please help to make it. @Starnop 

It is one topic in https://github.com/dragonflyoss/Dragonfly/issues/527

Related issue: #197
## Contact Us:
Dragonfly-SoC2019 Dingtalk:
<img src="https://user-images.githubusercontent.com/2419214/59184831-8a6e7100-8ba1-11e9-8e40-2bb48cd70ce8.png" width=250/>

**Comment by TG1999** [comment]
Hi I want to work on this project in Alibaba Summer of Code. So can you tell me what are perquisites for this project. And how can I show my pro efficiency for getting selected in this project.

**Comment by TG1999** [comment]
Please reply @allencloud

**Comment by fengzixu** [comment]
If the project(SoC2019) needs collaboration, you can talk to me @allencloud  ：）

**Comment by yeya24** [comment]
@allencloud  Hi, I' m interested in implementing this feature. And I see that currently the progress of refactoring of supernode is slow. Do I have to implement this feature for both Go and Java version of supernode?

**Comment by allencloud** [comment]
> Do I have to implement this feature for both Go and Java version of supernode?

We just need to implement the Golang version. Thanks. @yeya24

**Comment by cnTedMa** [comment]
Hi, I'm a graduate students, I‘d like to work on this project in ASoC(2019). What do I need to submit for applying？

**Comment by allencloud** [comment]
@cnTedMa , Please refer to @lowzj

**Comment by Starnop** [comment]
@allencloud After a discussion with @lowzj offline, we found that the metric definition is a good test for participants, so we should not provide the metrics for now. And we can put forward some opinions on the basis of the author's proposal when it comes to coding stage. WDYT?

**Comment by yeya24** [comment]
I think this is already solved. Close now.
