### ISSUE TITLE
Client failed to connect super node

### ISSUE THREAD

**Issue by junruyi** [dragonflyoss/Dragonfly#609]
## Question

![image](https://user-images.githubusercontent.com/28618485/59546192-ffec8f80-8f5b-11e9-8bae-1e63f3e4e009.png)
Super Node: 10.68.32.62 docker deployment

// 超级节点: 10.68.32.62    docker部署 

Client Node: 10.68.40.58 General Installation of df-client

// 客户端节点:10.68.40.58  普通安装df-client 

When using dfget -- URL "http://ip/hello.txt" -- node "10.68.32.62" -- console, the connection is displayed to 172.17.0.2

// 当使用 dfget --url "http://ip/hello.txt"  --node "10.68.32.62"   --console    时显示连接到172.17.0.2 

Timeout, 172.17.0.2 is the IP in docker.

// 超时， 172.17.0.2为超级节点docker里面的ip . 

Why is the consultation not directly connected to 10.68.32.62, but to 172.17.0.2? Is there a mistake in my deployment configuration?

// 咨询为何不是直接连到10.68.32.62，而是连到172.17.0.2上？ 是否是我部署配置有错误？

***!!!!WE STRONGLY ENCOURAGE YOU TO DESCRIBE YOUR ISSUE IN ENGLISH!!!!***

**Comment by lowzj** [comment]
添加参数 `-Dsupernode.advertiseIp= 10.68.32.62 `，指定ip

**Comment by junruyi** [comment]
可以了，谢谢~
