### ISSUE TITLE
make unit-test failed

### ISSUE THREAD

**Issue by casparant** [dragonflyoss/Dragonfly#631]
### Ⅰ. Issue Description

`make unit-test` encountered failures and stopped. The failures report as follows:

failure 1 & 2:

```
----------------------------------------------------------------------
FAIL: file_util_test.go:49: FileUtilTestSuite.TestCreateDirectory

file_util_test.go:61:
    c.Assert(err, check.NotNil)
... value = nil


----------------------------------------------------------------------
FAIL: file_util_test.go:209: FileUtilTestSuite.TestMd5sum

file_util_test.go:213:
    c.Assert(pathStrMd5, check.Equals, "")
... obtained string = "d41d8cd98f00b204e9800998ecf8427e"
... expected string = ""

bytes=0-65575
bytes=2-2
bytes=2-
bytes=-100
bytes=0-66575
bytes=0-65-575
bytes=0-hello
bytes=65575-0
bytes=-1-8
OOPS: 42 passed, 2 FAILED
--- FAIL: Test (7.88s)
FAIL
coverage: 58.3% of statements
FAIL    github.com/dragonflyoss/Dragonfly/common/util   7.901s
```

failure 3:

```
# github.com/dragonflyoss/Dragonfly/supernode/daemon/util
supernode/daemon/util/filter.go:60: Wrapf format %s has arg pageNum of wrong type int
supernode/daemon/util/filter.go:67: Wrapf format %s has arg pageSize of wrong type int
supernode/daemon/util/filter.go:108: Wrapf format %s has arg pageFilter.PageNum of wrong type int
supernode/daemon/util/filter.go:113: Wrapf format %s has arg pageFilter.PageSize of wrong type int
FAIL    github.com/dragonflyoss/Dragonfly/supernode/daemon/util [build failed]
```

### Ⅱ. Describe what happened
I am producing RPM packages for Dragonfly, a unit-test phase in `%check` section inside an RPM spec is mandatory. However, I fail to build it since the `make unit-test` reports errors above.

### Ⅲ. Describe what you expected to happen
`make unit-test` should pass.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. `export GOPATH=/path/to/some/go/path`
2. extract Dragonfly source tarball to `$GOPATH/src/github.com/dragonflyoss/Dragonfly`
3. cd to `$GOPATH/src/github.com/dragonflyoss/Dragonfly` and run `make unit-test`

### Ⅴ. Anything else we need to know?
N/A

### Ⅵ. Environment:

- dragonfly version: [0.4.0](https://github.com/dragonflyoss/Dragonfly/releases/tag/v0.4.0)
- OS (e.g. from /etc/os-release):
```
# cat /etc/os-release
NAME="Aliyun Linux"
VERSION="2.1903 (Hunting Beagle)"
ID="alinux"
ID_LIKE="rhel fedora centos"
VERSION_ID="2.1903"
PRETTY_NAME="Aliyun Linux 2.1903 (Hunting Beagle)"
ANSI_COLOR="0;31"
HOME_URL="https://www.aliyun.com/"
```
- Kernel (e.g. `uname -a`): `4.19.43-13.1.al7.x86_64`
- Install tools: 
```
# go version
go version go1.12 linux/amd64
```
- Others:

**Comment by lowzj** [comment]
I will fix it later.
