### ISSUE TITLE
[doc incomplete] Error through quick_start doc

### ISSUE THREAD

**Issue by yeya24** [dragonflyoss/Dragonfly#643]
### Ⅰ. Issue Description
Cannot success through quick_start doc.

### Ⅱ. Describe what happened
Cannot reproduce through quick_start and I found an error in the logs by `docker exec dfclient cat /root/.small-dragonfly/logs/dfclient.log`.
```
2019-07-01 08:48:00.159 ERRO sign:24-1561970880.159 : Connect to node:127.0.0.1:8002 error: dial tcp 127.0.0.1:8002: connect: connection refused
```
Dfget cannot access localhost:8082 because dfget and supernode are in different containers so they have their own localhost.

IMO one of the solutions is to specify the supernode ip via `--node` when starting dfclient container.

### Ⅲ. Describe what you expected to happen
Can see the downloading logs just as the quick_start shows.
```
downloading piece:{"taskID":"00a0503ea12457638ebbef5d0bfae51f9e8e0a0a349312c211f26f53beb93cdc","superNode":"127.0.0.1","dstCid":"127.0.0.1-95953-1553845720.488","range":"67108864-71303167","result":503,"status":701,"pieceSize":4194304,"pieceNum":16}
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- dragonfly version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by yunfeiyangbuaa** [comment]
I have test it works and the previous guide is wrong
