### ISSUE TITLE
[feature request] add minrate option for dfget 

### ISSUE THREAD

**Issue by jyizheng** [dragonflyoss/Dragonfly#648]
## Why you need it?

Let the client (dfget) to set the minimal rate, the default value can be 64 KB/s.

**Comment by allencloud** [comment]
Why you need it? If we do not have this feature, what shortcomings will be brought to the end users? 
Could you be more specific? @jyizheng

**Comment by jyizheng** [comment]
Currently, the minimal download speed of Dragonfly is 64 KB/s,  and Dragonfly uses this
number and the file size to estimate the total time of downloading a file. Some machines
may have very low download speed (<64 KB/s). For these machines, it could be useful to specify
"minrate" when running dfget so that they will not encounter TIMEOUT.

**Comment by yeya24** [comment]
We can close this via https://github.com/dragonflyoss/Dragonfly/pull/664

**Comment by allencloud** [comment]
> We can close this via #664

Yes.
