### ISSUE TITLE
build doc for go version dragonfly

### ISSUE THREAD

**Issue by xzy256** [dragonflyoss/Dragonfly#676]
When i need build go version dragonfly, i find not doc for reference like  [Installing Dragonfly Server](https://d7y.io/zh-cn/docs/userguide/install_server.html). It is Inducible that accorde to build java version dragonfly doc.

**Comment by yeya24** [comment]
You can check this [Install Dragonfly Server Go](https://github.com/dragonflyoss/Dragonfly/blob/master/docs/user_guide/install_server_go.md) doc.

**Comment by xzy256** [comment]
great,  thx.

**Comment by xzy256** [comment]
By the way,  do `dragonflyoss/supernode:0.4.0`  merge pull request  #671 ?

**Comment by yeya24** [comment]
> By the way, do `dragonflyoss/supernode:0.4.0` merge pull request #671 ?

This PR is not merged yet, so it is not included in 0.4.0. And currently the latest release is 0.4.1, you can use image dragonflyoss/supernode:0.4.1.

**Comment by xzy256** [comment]
Ok.  I build success by myself according to [Install Dragonfly Server Go](https://github.com/dragonflyoss/Dragonfly/blob/master/docs/user_guide/install_server_go.md). Then i close this issue. Thanks for your attention.
