### ISSUE TITLE
[bug]dfget's supernode API return err

### ISSUE THREAD

**Issue by yunfeiyangbuaa** [dragonflyoss/Dragonfly#680]
### Ⅰ. Issue Description
the two [dfget's supernode api](https://github.com/dragonflyoss/Dragonfly/blob/21d2390907a870c2fa51c9d721ca464127c379b5/dfget/core/api/supernode_api.go#L98) will return a json parsing error，but the coder ignores it.
```
func (api *supernodeAPI) ServiceDown(node string, taskID string, cid string) (
	resp *types.BaseResponse, e error) {
func (api *supernodeAPI) ReportPiece(node string, req *types.ReportPieceRequest) (
	resp *types.BaseResponse, e error) {
```
so when dfget[ use these api](https://github.com/dragonflyoss/Dragonfly/blob/21d2390907a870c2fa51c9d721ca464127c379b5/dfget/core/downloader/p2p_downloader/client_writer.go#L198),it ignore the error
```
cw.api.ReportPiece(piece.SuperNode, &types.ReportPieceRequest{
		TaskID:     piece.TaskID,
		Cid:        cw.cfg.RV.Cid,
		DstCid:     piece.DstCid,
		PieceRange: piece.Range,
})
if cost.Seconds() > 2.0 {
		logrus.Infof(
		"async writer and report suc from dst:%s... cost:%.3f for range:%s",
		piece.DstCid[:25], cost.Seconds(), piece.Range)
 }

if ok {
	ps.api.ServiceDown(task.superNode, task.taskID, task.cid)
	serviceFile := helper.GetServiceFile(key.(string), task.dataDir)
	os.Remove(serviceFile)
	logrus.Infof("shutdown, remove task id:%s file:%s",
	task.taskID, serviceFile)
}
```
### Ⅱ. Describe what happened
error happen but we haven't do with it

### Ⅲ. Describe what you expected to happen

when we use these api,we can do with the error
### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- dragonfly version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by allencloud** [comment]
You should add a code link reference for the code block you attached. Because of that, we can find the  code block's context very easily. @yunfeiyangbuaa

**Comment by yunfeiyangbuaa** [comment]
> You should add a code link reference for the code block you attached. Because of that, we can find the code block's context very easily. @yunfeiyangbuaa

**Comment by yunfeiyangbuaa** [comment]
> You should add a code link reference for the code block you attached. Because of that, we can find the code block's context very easily. @yunfeiyangbuaa

Done
