### ISSUE TITLE
what kind of http server runs on the client side? 

### ISSUE THREAD

**Issue by tirupatibg** [dragonflyoss/Dragonfly#685]
## Question
I see that spring boot application runs the embedded tomcat on the super node side. But what kind of http service runs on the client side to sever the peer nodes?

**Comment by allencloud** [comment]
Currently we suggest users come to use Dragonfly 0.4.x. And It is totally rewrittern withi Golang. So there is no spring boot related staff inside of Dragonfly. 
While before version 0.4.0, Dragonfly-supernode is written in Java, dfdaemon and dfget are in Python and Golang. Now all in Golang. @tirupatibg

**Comment by tirupatibg** [comment]
Thanks @allencloud for sharing the info
I don't see the the branch 0.4.x in GitHub. where can i get this branch?

**Comment by allencloud** [comment]
Actually latest branch master is the version 0.4.x. This is the correct one you should use. @tirupatibg

**Comment by tirupatibg** [comment]
@allencloud But when i try to build the master. Build getting failed. I tried to set up server using go.

Not sure whether master is in working condition or not.
NOTE: The Golang version supernode is not ready for production usage. However, you can use it more easily in your test environment.

Here is is exception trace:
Begin to build supernode.
./hack/build.sh supernode
Begin to build in the local environment.
go: finding github.com/go-openapi/loads v0.0.0-20170520182102-a80dea3052f0
go: finding github.com/mitchellh/mapstructure v1.1.2
go: finding github.com/inconshreveable/mousetrap v1.0.0
go: finding gopkg.in/yaml.v2 v2.2.2
go: finding gopkg.in/gcfg.v1 v1.2.3
go: finding github.com/go-openapi/swag v0.0.0-20170606142751-f3f9494671f9
go: finding github.com/go-openapi/jsonreference v0.0.0-20161105162150-36d33bfe519e
go: finding github.com/gorilla/mux v1.5.0
go: finding github.com/pkg/errors v0.8.0
go: finding github.com/go-openapi/validate v0.0.0-20170705144413-8a82927c942c
go: gopkg.in/gcfg.v1@v1.2.3: Get https://goproxy.io/gopkg.in/gcfg.v1/@v/v1.2.3.info: net/http: TLS handshake timeout
go: github.com/go-openapi/jsonreference@v0.0.0-20161105162150-36d33bfe519e: Get https://goproxy.io/github.com/go-openapi/jsonreference/@v/v0.0.0-20161105162150-36d33bfe519e.info: net/http: TLS handshake timeout
go: github.com/go-openapi/loads@v0.0.0-20170520182102-a80dea3052f0: Get https://goproxy.io/github.com/go-openapi/loads/@v/v0.0.0-20170520182102-a80dea3052f0.info: net/http: TLS handshake timeout
go: github.com/pkg/errors@v0.8.0: Get https://goproxy.io/github.com/pkg/errors/@v/v0.8.0.info: net/http: TLS handshake timeout
go: finding github.com/go-check/check v0.0.0-20161208181325-20d25e280405
go: github.com/gorilla/mux@v1.5.0: Get https://goproxy.io/github.com/gorilla/mux/@v/v1.5.0.info: net/http: TLS handshake timeout
go: github.com/go-openapi/swag@v0.0.0-20170606142751-f3f9494671f9: Get https://goproxy.io/github.com/go-openapi/swag/@v/v0.0.0-20170606142751-f3f9494671f9.info: net/http: TLS handshake timeout
go: finding github.com/willf/bitset v0.0.0-20190228212526-18bd95f470f9
go: finding github.com/pborman/uuid v0.0.0-20180122190007-c65b2f87fee3
go: finding github.com/prashantv/gostub v1.0.0
go: finding github.com/cpuguy83/go-md2man v1.0.7
go: gopkg.in/yaml.v2@v2.2.2: Get https://goproxy.io/gopkg.in/yaml.v2/@v/v2.2.2.info: net/http: TLS handshake timeout
go: finding github.com/go-openapi/spec v0.0.0-20170811033243-3faa0055dbbf
go: finding github.com/valyala/fasthttp v1.3.0
go: github.com/mitchellh/mapstructure@v1.1.2: Get https://goproxy.io/github.com/mitchellh/mapstructure/@v/v1.1.2.info: net/http: TLS handshake timeout
go: github.com/go-openapi/validate@v0.0.0-20170705144413-8a82927c942c: Get https://goproxy.io/github.com/go-openapi/validate/@v/v0.0.0-20170705144413-8a82927c942c.info: net/http: TLS handshake timeout
go: finding github.com/magiconair/properties v1.8.1
go: finding github.com/go-openapi/analysis v0.0.0-20170813233457-8ed83f2ea9f0
go: github.com/inconshreveable/mousetrap@v1.0.0: Get https://goproxy.io/github.com/inconshreveable/mousetrap/@v/v1.0.0.info: net/http: TLS handshake timeout
go: finding github.com/golang/mock v1.3.1
go: github.com/willf/bitset@v0.0.0-20190228212526-18bd95f470f9: Get https://goproxy.io/github.com/willf/bitset/@v/v0.0.0-20190228212526-18bd95f470f9.info: net/http: TLS handshake timeout
go: github.com/go-openapi/spec@v0.0.0-20170811033243-3faa0055dbbf: Get https://goproxy.io/github.com/go-openapi/spec/@v/v0.0.0-20170811033243-3faa0055dbbf.info: net/http: TLS handshake timeout
go: github.com/go-check/check@v0.0.0-20161208181325-20d25e280405: Get https://goproxy.io/github.com/go-check/check/@v/v0.0.0-20161208181325-20d25e280405.info: net/http: TLS handshake timeout
go: finding github.com/asaskevich/govalidator v0.0.0-20170903095215-73945b6115bf
go: github.com/valyala/fasthttp@v1.3.0: Get https://goproxy.io/github.com/valyala/fasthttp/@v/v1.3.0.info: net/http: TLS handshake timeout
go: finding github.com/stretchr/testify v1.2.2
go: finding github.com/spf13/cobra v0.0.0-20181021141114-fe5e611709b0
go: github.com/pborman/uuid@v0.0.0-20180122190007-c65b2f87fee3: Get https://goproxy.io/github.com/pborman/uuid/@v/v0.0.0-20180122190007-c65b2f87fee3.info: net/http: TLS handshake timeout
go: finding gopkg.in/mgo.v2 v2.0.0-20160818020120-3f83fa500528
go: finding github.com/go-openapi/jsonpointer v0.0.0-20170102174223-779f45308c19
go: github.com/golang/mock@v1.3.1: Get https://goproxy.io/github.com/golang/mock/@v/v1.3.1.info: net/http: TLS handshake timeout
go: github.com/prashantv/gostub@v1.0.0: Get https://goproxy.io/github.com/prashantv/gostub/@v/v1.0.0.info: net/http: TLS handshake timeout
go: finding github.com/PuerkitoBio/urlesc v0.0.0-20170810143723-de5bf2ad4578
go: finding github.com/go-openapi/runtime v0.0.0-20170901133030-bf2ff8f71507
go: github.com/cpuguy83/go-md2man@v1.0.7: Get https://goproxy.io/github.com/cpuguy83/go-md2man/@v/v1.0.7.info: net/http: TLS handshake timeout
go: finding github.com/go-openapi/errors v0.0.0-20170426151106-03cfca65330d
go: github.com/magiconair/properties@v1.8.1: Get https://goproxy.io/github.com/magiconair/properties/@v/v1.8.1.info: net/http: TLS handshake timeout
go: finding gopkg.in/warnings.v0 v0.1.2
go: github.com/go-openapi/analysis@v0.0.0-20170813233457-8ed83f2ea9f0: Get https://goproxy.io/github.com/go-openapi/analysis/@v/v0.0.0-20170813233457-8ed83f2ea9f0.info: net/http: TLS handshake timeout
go: finding github.com/prometheus/client_golang v0.9.3
go: github.com/stretchr/testify@v1.2.2: Get https://goproxy.io/github.com/stretchr/testify/@v/v1.2.2.info: net/http: TLS handshake timeout
go: github.com/PuerkitoBio/urlesc@v0.0.0-20170810143723-de5bf2ad4578: Get https://goproxy.io/github.com/%21puerkito%21bio/urlesc/@v/v0.0.0-20170810143723-de5bf2ad4578.info: net/http: TLS handshake timeout
go: finding github.com/russross/blackfriday v0.0.0-20171011182219-6d1ef893fcb0
go: finding github.com/spf13/jwalterweatherman v1.1.0
go: github.com/go-openapi/jsonpointer@v0.0.0-20170102174223-779f45308c19: Get https://goproxy.io/github.com/go-openapi/jsonpointer/@v/v0.0.0-20170102174223-779f45308c19.info: net/http: TLS handshake timeout
go: finding github.com/spf13/afero v1.2.2
go: github.com/go-openapi/runtime@v0.0.0-20170901133030-bf2ff8f71507: Get https://goproxy.io/github.com/go-openapi/runtime/@v/v0.0.0-20170901133030-bf2ff8f71507.info: net/http: TLS handshake timeout
go: finding github.com/gorilla/context v0.0.0-20181012153548-51ce91d2eadd
go: gopkg.in/mgo.v2@v2.0.0-20160818020120-3f83fa500528: Get https://goproxy.io/gopkg.in/mgo.v2/@v/v2.0.0-20160818020120-3f83fa500528.info: net/http: TLS handshake timeout
go: github.com/spf13/cobra@v0.0.0-20181021141114-fe5e611709b0: Get https://goproxy.io/github.com/spf13/cobra/@v/v0.0.0-20181021141114-fe5e611709b0.info: net/http: TLS handshake timeout
go: finding github.com/go-openapi/strfmt v0.0.0-20171222154016-4dd3d302e100
go: finding github.com/spf13/viper v1.4.0
go: github.com/asaskevich/govalidator@v0.0.0-20170903095215-73945b6115bf: Get https://goproxy.io/github.com/asaskevich/govalidator/@v/v0.0.0-20170903095215-73945b6115bf.info: net/http: TLS handshake timeout
go: finding github.com/mailru/easyjson v0.0.0-20170902151237-2a92e673c9a6
go: gopkg.in/warnings.v0@v0.1.2: Get https://goproxy.io/gopkg.in/warnings.v0/@v/v0.1.2.info: net/http: TLS handshake timeout
go: finding github.com/sirupsen/logrus v1.2.0
go: github.com/go-openapi/errors@v0.0.0-20170426151106-03cfca65330d: Get https://goproxy.io/github.com/go-openapi/errors/@v/v0.0.0-20170426151106-03cfca65330d.info: net/http: TLS handshake timeout
go: finding github.com/PuerkitoBio/purell v0.0.0-20170829232023-f619812e3caf
go: github.com/prometheus/client_golang@v0.9.3: Get https://goproxy.io/github.com/prometheus/client_golang/@v/v0.9.3.info: net/http: TLS handshake timeout
go: github.com/go-openapi/strfmt@v0.0.0-20171222154016-4dd3d302e100: Get https://goproxy.io/github.com/go-openapi/strfmt/@v/v0.0.0-20171222154016-4dd3d302e100.info: net/http: TLS handshake timeout
go: github.com/gorilla/context@v0.0.0-20181012153548-51ce91d2eadd: Get https://goproxy.io/github.com/gorilla/context/@v/v0.0.0-20181012153548-51ce91d2eadd.info: net/http: TLS handshake timeout
go: github.com/spf13/afero@v1.2.2: Get https://goproxy.io/github.com/spf13/afero/@v/v1.2.2.info: net/http: TLS handshake timeout
go: github.com/spf13/viper@v1.4.0: Get https://goproxy.io/github.com/spf13/viper/@v/v1.4.0.info: net/http: TLS handshake timeout
go: github.com/spf13/jwalterweatherman@v1.1.0: Get https://goproxy.io/github.com/spf13/jwalterweatherman/@v/v1.1.0.info: net/http: TLS handshake timeout
go: github.com/russross/blackfriday@v0.0.0-20171011182219-6d1ef893fcb0: Get https://goproxy.io/github.com/russross/blackfriday/@v/v0.0.0-20171011182219-6d1ef893fcb0.info: net/http: TLS handshake timeout
go: github.com/PuerkitoBio/purell@v0.0.0-20170829232023-f619812e3caf: Get https://goproxy.io/github.com/%21puerkito%21bio/purell/@v/v0.0.0-20170829232023-f619812e3caf.info: net/http: TLS handshake timeout
go: github.com/sirupsen/logrus@v1.2.0: Get https://goproxy.io/github.com/sirupsen/logrus/@v/v1.2.0.info: net/http: TLS handshake timeout
go: github.com/mailru/easyjson@v0.0.0-20170902151237-2a92e673c9a6: Get https://goproxy.io/github.com/mailru/easyjson/@v/v0.0.0-20170902151237-2a92e673c9a6.info: net/http: TLS handshake timeout
go: error loading module requirements
chmod: cannot access '/root/go/src/github.com/dragonflyoss/Dragonfly/bin/linux_amd64/supernode': No such file or directory
BUILD: supernode in /root/go/src/github.com/dragonflyoss/Dragonfly/bin/linux_amd64/supernode
root@tirupati-virtual-machine:~/go/src/github.com/dragonflyoss/Dragonfly# make build-supernode
root@tirupati-virtual-machine:~/go/src/github.com/dragonflyoss/Dragonfly# make build-supernode
Begin to build supernode.
./hack/build.sh supernode
Begin to build in the local environment.
go: finding github.com/go-openapi/validate v0.0.0-20170705144413-8a82927c942c
go: finding github.com/go-openapi/strfmt v0.0.0-20171222154016-4dd3d302e100
go: finding github.com/PuerkitoBio/urlesc v0.0.0-20170810143723-de5bf2ad4578
go: finding github.com/magiconair/properties v1.8.1
go: finding github.com/inconshreveable/mousetrap v1.0.0
go: finding github.com/go-openapi/jsonreference v0.0.0-20161105162150-36d33bfe519e
go: finding github.com/russross/blackfriday v0.0.0-20171011182219-6d1ef893fcb0
go: finding github.com/go-openapi/jsonpointer v0.0.0-20170102174223-779f45308c19
go: finding gopkg.in/yaml.v2 v2.2.2
go: finding github.com/golang/mock v1.3.1
go: gopkg.in/yaml.v2@v2.2.2: Get https://goproxy.io/gopkg.in/yaml.v2/@v/v2.2.2.info: net/http: TLS handshake timeout
go: github.com/golang/mock@v1.3.1: Get https://goproxy.io/github.com/golang/mock/@v/v1.3.1.info: net/http: TLS handshake timeout
go: github.com/PuerkitoBio/urlesc@v0.0.0-20170810143723-de5bf2ad4578: Get https://goproxy.io/github.com/%21puerkito%21bio/urlesc/@v/v0.0.0-20170810143723-de5bf2ad4578.info: net/http: TLS handshake timeout
go: finding github.com/go-check/check v0.0.0-20161208181325-20d25e280405
go: github.com/go-openapi/strfmt@v0.0.0-20171222154016-4dd3d302e100: Get https://goproxy.io/github.com/go-openapi/strfmt/@v/v0.0.0-20171222154016-4dd3d302e100.info: net/http: TLS handshake timeout
go: finding github.com/prometheus/client_golang v0.9.3
go: github.com/russross/blackfriday@v0.0.0-20171011182219-6d1ef893fcb0: Get https://goproxy.io/github.com/russross/blackfriday/@v/v0.0.0-20171011182219-6d1ef893fcb0.info: net/http: TLS handshake timeout
go: finding github.com/sirupsen/logrus v1.2.0
go: finding github.com/prashantv/gostub v1.0.0
go: github.com/go-openapi/jsonpointer@v0.0.0-20170102174223-779f45308c19: Get https://goproxy.io/github.com/go-openapi/jsonpointer/@v/v0.0.0-20170102174223-779f45308c19.info: net/http: TLS handshake timeout
go: finding gopkg.in/warnings.v0 v0.1.2
go: finding github.com/cpuguy83/go-md2man v1.0.7
go: github.com/magiconair/properties@v1.8.1: Get https://goproxy.io/github.com/magiconair/properties/@v/v1.8.1.info: net/http: TLS handshake timeout
go: github.com/go-openapi/jsonreference@v0.0.0-20161105162150-36d33bfe519e: Get https://goproxy.io/github.com/go-openapi/jsonreference/@v/v0.0.0-20161105162150-36d33bfe519e.info: net/http: TLS handshake timeout
go: finding gopkg.in/mgo.v2 v2.0.0-20160818020120-3f83fa500528
go: github.com/inconshreveable/mousetrap@v1.0.0: Get https://goproxy.io/github.com/inconshreveable/mousetrap/@v/v1.0.0.info: net/http: TLS handshake timeout
go: finding github.com/mitchellh/mapstructure v1.1.2
go: github.com/go-openapi/validate@v0.0.0-20170705144413-8a82927c942c: Get https://goproxy.io/github.com/go-openapi/validate/@v/v0.0.0-20170705144413-8a82927c942c.info: net/http: TLS handshake timeout
go: finding github.com/go-openapi/analysis v0.0.0-20170813233457-8ed83f2ea9f0
go: finding github.com/gorilla/context v0.0.0-20181012153548-51ce91d2eadd
go: github.com/prashantv/gostub@v1.0.0: Get https://goproxy.io/github.com/prashantv/gostub/@v/v1.0.0.info: net/http: TLS handshake timeout
go: github.com/go-openapi/analysis@v0.0.0-20170813233457-8ed83f2ea9f0: Get https://goproxy.io/github.com/go-openapi/analysis/@v/v0.0.0-20170813233457-8ed83f2ea9f0.info: net/http: TLS handshake timeout
go: github.com/prometheus/client_golang@v0.9.3: Get https://goproxy.io/github.com/prometheus/client_golang/@v/v0.9.3.info: net/http: TLS handshake timeout
go: finding github.com/asaskevich/govalidator v0.0.0-20170903095215-73945b6115bf
go: finding github.com/stretchr/testify v1.2.2
go: finding gopkg.in/gcfg.v1 v1.2.3
go: github.com/cpuguy83/go-md2man@v1.0.7: Get https://goproxy.io/github.com/cpuguy83/go-md2man/@v/v1.0.7.info: net/http: TLS handshake timeout
go: github.com/gorilla/context@v0.0.0-20181012153548-51ce91d2eadd: Get https://goproxy.io/github.com/gorilla/context/@v/v0.0.0-20181012153548-51ce91d2eadd.info: net/http: TLS handshake timeout
go: github.com/sirupsen/logrus@v1.2.0: Get https://goproxy.io/github.com/sirupsen/logrus/@v/v1.2.0.info: net/http: TLS handshake timeout
go: finding github.com/pkg/errors v0.8.0
go: gopkg.in/mgo.v2@v2.0.0-20160818020120-3f83fa500528: Get https://goproxy.io/gopkg.in/mgo.v2/@v/v2.0.0-20160818020120-3f83fa500528.info: net/http: TLS handshake timeout
go: github.com/go-check/check@v0.0.0-20161208181325-20d25e280405: Get https://goproxy.io/github.com/go-check/check/@v/v0.0.0-20161208181325-20d25e280405.info: net/http: TLS handshake timeout
go: github.com/mitchellh/mapstructure@v1.1.2: Get https://goproxy.io/github.com/mitchellh/mapstructure/@v/v1.1.2.info: net/http: TLS handshake timeout
go: finding github.com/go-openapi/spec v0.0.0-20170811033243-3faa0055dbbf
go: finding github.com/go-openapi/errors v0.0.0-20170426151106-03cfca65330d
go: gopkg.in/warnings.v0@v0.1.2: Get https://goproxy.io/gopkg.in/warnings.v0/@v/v0.1.2.info: net/http: TLS handshake timeout
go: finding github.com/mailru/easyjson v0.0.0-20170902151237-2a92e673c9a6
go: finding github.com/spf13/afero v1.2.2
go: finding github.com/go-openapi/loads v0.0.0-20170520182102-a80dea3052f0
go: finding github.com/go-openapi/runtime v0.0.0-20170901133030-bf2ff8f71507
go: github.com/go-openapi/loads@v0.0.0-20170520182102-a80dea3052f0: Get https://goproxy.io/github.com/go-openapi/loads/@v/v0.0.0-20170520182102-a80dea3052f0.info: net/http: TLS handshake timeout
go: finding github.com/spf13/cobra v0.0.0-20181021141114-fe5e611709b0
go: gopkg.in/gcfg.v1@v1.2.3: Get https://goproxy.io/gopkg.in/gcfg.v1/@v/v1.2.3.info: net/http: TLS handshake timeout
go: github.com/go-openapi/errors@v0.0.0-20170426151106-03cfca65330d: Get https://goproxy.io/github.com/go-openapi/errors/@v/v0.0.0-20170426151106-03cfca65330d.info: net/http: TLS handshake timeout
go: github.com/mailru/easyjson@v0.0.0-20170902151237-2a92e673c9a6: Get https://goproxy.io/github.com/mailru/easyjson/@v/v0.0.0-20170902151237-2a92e673c9a6.info: net/http: TLS handshake timeout
go: github.com/spf13/afero@v1.2.2: Get https://goproxy.io/github.com/spf13/afero/@v/v1.2.2.info: net/http: TLS handshake timeout
go: github.com/pkg/errors@v0.8.0: Get https://goproxy.io/github.com/pkg/errors/@v/v0.8.0.info: net/http: TLS handshake timeout
go: github.com/stretchr/testify@v1.2.2: Get https://goproxy.io/github.com/stretchr/testify/@v/v1.2.2.info: net/http: TLS handshake timeout
go: github.com/go-openapi/runtime@v0.0.0-20170901133030-bf2ff8f71507: Get https://goproxy.io/github.com/go-openapi/runtime/@v/v0.0.0-20170901133030-bf2ff8f71507.info: net/http: TLS handshake timeout
go: github.com/asaskevich/govalidator@v0.0.0-20170903095215-73945b6115bf: Get https://goproxy.io/github.com/asaskevich/govalidator/@v/v0.0.0-20170903095215-73945b6115bf.info: net/http: TLS handshake timeout
go: github.com/go-openapi/spec@v0.0.0-20170811033243-3faa0055dbbf: Get https://goproxy.io/github.com/go-openapi/spec/@v/v0.0.0-20170811033243-3faa0055dbbf.info: net/http: TLS handshake timeout
go: finding github.com/gorilla/mux v1.5.0
go: finding github.com/PuerkitoBio/purell v0.0.0-20170829232023-f619812e3caf
go: finding github.com/go-openapi/swag v0.0.0-20170606142751-f3f9494671f9
go: finding github.com/valyala/fasthttp v1.3.0
go: finding github.com/willf/bitset v0.0.0-20190228212526-18bd95f470f9
go: finding github.com/pborman/uuid v0.0.0-20180122190007-c65b2f87fee3
go: finding github.com/spf13/jwalterweatherman v1.1.0
go: finding github.com/spf13/viper v1.4.0
go: github.com/pborman/uuid@v0.0.0-20180122190007-c65b2f87fee3: Get https://goproxy.io/github.com/pborman/uuid/@v/v0.0.0-20180122190007-c65b2f87fee3.info: net/http: TLS handshake timeout
go: github.com/spf13/cobra@v0.0.0-20181021141114-fe5e611709b0: Get https://goproxy.io/github.com/spf13/cobra/@v/v0.0.0-20181021141114-fe5e611709b0.info: net/http: TLS handshake timeout
go: github.com/spf13/jwalterweatherman@v1.1.0: Get https://goproxy.io/github.com/spf13/jwalterweatherman/@v/v1.1.0.info: net/http: TLS handshake timeout
go: github.com/willf/bitset@v0.0.0-20190228212526-18bd95f470f9: Get https://goproxy.io/github.com/willf/bitset/@v/v0.0.0-20190228212526-18bd95f470f9.info: net/http: TLS handshake timeout
go: github.com/valyala/fasthttp@v1.3.0: Get https://goproxy.io/github.com/valyala/fasthttp/@v/v1.3.0.info: net/http: TLS handshake timeout
go: github.com/go-openapi/swag@v0.0.0-20170606142751-f3f9494671f9: Get https://goproxy.io/github.com/go-openapi/swag/@v/v0.0.0-20170606142751-f3f9494671f9.info: net/http: TLS handshake timeout
go: github.com/PuerkitoBio/purell@v0.0.0-20170829232023-f619812e3caf: Get https://goproxy.io/github.com/%21puerkito%21bio/purell/@v/v0.0.0-20170829232023-f619812e3caf.info: net/http: TLS handshake timeout
go: github.com/gorilla/mux@v1.5.0: Get https://goproxy.io/github.com/gorilla/mux/@v/v1.5.0.info: net/http: TLS handshake timeout
go: github.com/spf13/viper@v1.4.0: Get https://goproxy.io/github.com/spf13/viper/@v/v1.4.0.info: net/http: TLS handshake timeout
go: error loading module requirements
chmod: cannot access '/root/go/src/github.com/dragonflyoss/Dragonfly/bin/linux_amd64/supernode': No such file or directory
BUILD: supernode in /root/go/src/github.com/dragonflyoss/Dragonfly/bin/linux_amd64/supernode

**Comment by lowzj** [comment]
please use the latest code to build, we optimize the compile scripts to use GOPROXY to accelerate downloading the third-party go package.
