### ISSUE TITLE
[feature request] provide a more flexible way to pass parameter from dfdaemon to dfget

### ISSUE THREAD

**Issue by yeya24** [dragonflyoss/Dragonfly#687]
## Why you need it?

Currently we just directly pass the parameters from dfdaemon to dfget. However these flags are global and sometimes different proxies may need different parameters such as timeout or urlfilters.

We should provide a more flexible way to construct dfget parameters in dfdaemon.

## Other related information

Related: 
https://github.com/dragonflyoss/Dragonfly/pull/670
https://github.com/dragonflyoss/Dragonfly/pull/686

**Comment by Starnop** [comment]
Maybe we can add a string field for dfdaemon such as `dfgetParam` which will be passed to dfget just as @lowzj mentioned [here](https://github.com/dragonflyoss/Dragonfly/pull/670#pullrequestreview-262173464).

**Comment by lowzj** [comment]
The `dfgetParam` of a proxy inherits and overrides the `flags` of `dfdaemon` passed to `dfget`.

**Comment by yeya24** [comment]
Do we need that key-value map? What about just using k-v pair like `minrate: 20k`?

IMO if we want to use config files to pass variables, is it  confusing to still pass variables from dfdaemon flags? Maybe we can add a field of `globalParams` in configuration and remove most of flags from dfdaemon.

**Comment by Starnop** [comment]
> Do we need that key-value map? What about just using k-v pair like `minrate: 20k`?

I agree with that.

**Comment by Starnop** [comment]
> IMO if we want to use config files to pass variables, is it confusing to still pass variables from dfdaemon flags? Maybe we can add a field of `globalParams` in configuration and remove most of flags from dfdaemon.

Good suggestion. A globalParams is necessary and I think it's better to temporarily reserve the way to pass parameters via flag. WDYT?

So let's do these things next:
1. use config file to pass the values to dfget firstly and merge the configs from config file and flags.
2. provide a config template and with a script that automatically generates it

@lowzj @yeya24 Any other supplements？

**Comment by lowzj** [comment]
agree

**Comment by Starnop** [comment]
@yeya24 So would you like to do that? 😄

**Comment by yeya24** [comment]
Sure
/assign

**Comment by yeya24** [comment]
I have a question about how to deal with the config files between dfdaemon and dfget. If we set some dfgetParams, how we deal with dfget.yml?

**Comment by lowzj** [comment]
The properties of `dfget` from CLI flags have a higher priority than config files.
The priority of properties that `dfdfaemon` passed to `dfget`:
```bash
lower  | 1. `globalParams` in `dfdaemon` config file
       | 2. `dfdaemon` flags, they will override the `globalParams`
higher | 3. `dfgetParams` of every `proxy` property in `dfdaemon` config file
```

**Comment by lowzj** [comment]
I thinks this feature has already been implemented. I will close it, if not please reopen again.
