### ISSUE TITLE
GO - Unable to build the super node with master branch 

### ISSUE THREAD

**Issue by tirupatibg** [dragonflyoss/Dragonfly#693]
### Ⅳ. Steps to repro

1. git clone https://github.com/dragonflyoss/Dragonfly.git
2. cd Dragonfly
3. make build-supernode

### Ⅴ. Anything else we need to know?

go: finding github.com/go-openapi/validate v0.0.0-20170705144413-8a82927c942c
go: finding github.com/go-openapi/strfmt v0.0.0-20171222154016-4dd3d302e100
go: finding github.com/PuerkitoBio/urlesc v0.0.0-20170810143723-de5bf2ad4578
go: finding github.com/magiconair/properties v1.8.1
go: finding github.com/inconshreveable/mousetrap v1.0.0
go: finding github.com/go-openapi/jsonreference v0.0.0-20161105162150-36d33bfe519e
go: finding github.com/russross/blackfriday v0.0.0-20171011182219-6d1ef893fcb0
go: finding github.com/go-openapi/jsonpointer v0.0.0-20170102174223-779f45308c19
go: finding gopkg.in/yaml.v2 v2.2.2
go: finding github.com/golang/mock v1.3.1
go: gopkg.in/yaml.v2@v2.2.2: Get https://goproxy.io/gopkg.in/yaml.v2/@v/v2.2.2.info: net/http: TLS handshake timeout
go: github.com/golang/mock@v1.3.1: Get https://goproxy.io/github.com/golang/mock/@v/v1.3.1.info: net/http: TLS handshake timeout
go: github.com/PuerkitoBio/urlesc@v0.0.0-20170810143723-de5bf2ad4578: Get https://goproxy.io/github.com/%21puerkito%21bio/urlesc/@v/v0.0.0-20170810143723-de5bf2ad4578.info: net/http: TLS handshake timeout
go: finding github.com/go-check/check v0.0.0-20161208181325-20d25e280405
go: github.com/go-openapi/strfmt@v0.0.0-20171222154016-4dd3d302e100: Get https://goproxy.io/github.com/go-openapi/strfmt/@v/v0.0.0-20171222154016-4dd3d302e100.info: net/http: TLS handshake timeout
go: finding github.com/prometheus/client_golang v0.9.3
go: github.com/russross/blackfriday@v0.0.0-20171011182219-6d1ef893fcb0: Get https://goproxy.io/github.com/russross/blackfriday/@v/v0.0.0-20171011182219-6d1ef893fcb0.info: net/http: TLS handshake timeout
go: finding github.com/sirupsen/logrus v1.2.0
go: finding github.com/prashantv/gostub v1.0.0
go: github.com/go-openapi/jsonpointer@v0.0.0-20170102174223-779f45308c19: Get https://goproxy.io/github.com/go-openapi/jsonpointer/@v/v0.0.0-20170102174223-779f45308c19.info: net/http: TLS handshake timeout
go: finding gopkg.in/warnings.v0 v0.1.2
go: finding github.com/cpuguy83/go-md2man v1.0.7
go: github.com/magiconair/properties@v1.8.1: Get https://goproxy.io/github.com/magiconair/properties/@v/v1.8.1.info: net/http: TLS handshake timeout
go: github.com/go-openapi/jsonreference@v0.0.0-20161105162150-36d33bfe519e: Get https://goproxy.io/github.com/go-openapi/jsonreference/@v/v0.0.0-20161105162150-36d33bfe519e.info: net/http: TLS handshake timeout
go: finding gopkg.in/mgo.v2 v2.0.0-20160818020120-3f83fa500528
go: github.com/inconshreveable/mousetrap@v1.0.0: Get https://goproxy.io/github.com/inconshreveable/mousetrap/@v/v1.0.0.info: net/http: TLS handshake timeout
go: finding github.com/mitchellh/mapstructure v1.1.2
go: github.com/go-openapi/validate@v0.0.0-20170705144413-8a82927c942c: Get https://goproxy.io/github.com/go-openapi/validate/@v/v0.0.0-20170705144413-8a82927c942c.info: net/http: TLS handshake timeout
go: finding github.com/go-openapi/analysis v0.0.0-20170813233457-8ed83f2ea9f0
go: finding github.com/gorilla/context v0.0.0-20181012153548-51ce91d2eadd
go: github.com/prashantv/gostub@v1.0.0: Get https://goproxy.io/github.com/prashantv/gostub/@v/v1.0.0.info: net/http: TLS handshake timeout
go: github.com/go-openapi/analysis@v0.0.0-20170813233457-8ed83f2ea9f0: Get https://goproxy.io/github.com/go-openapi/analysis/@v/v0.0.0-20170813233457-8ed83f2ea9f0.info: net/http: TLS handshake timeout
go: github.com/prometheus/client_golang@v0.9.3: Get https://goproxy.io/github.com/prometheus/client_golang/@v/v0.9.3.info: net/http: TLS handshake timeout
go: finding github.com/asaskevich/govalidator v0.0.0-20170903095215-73945b6115bf
go: finding github.com/stretchr/testify v1.2.2
go: finding gopkg.in/gcfg.v1 v1.2.3
go: github.com/cpuguy83/go-md2man@v1.0.7: Get https://goproxy.io/github.com/cpuguy83/go-md2man/@v/v1.0.7.info: net/http: TLS handshake timeout
go: github.com/gorilla/context@v0.0.0-20181012153548-51ce91d2eadd: Get https://goproxy.io/github.com/gorilla/context/@v/v0.0.0-20181012153548-51ce91d2eadd.info: net/http: TLS handshake timeout
go: github.com/sirupsen/logrus@v1.2.0: Get https://goproxy.io/github.com/sirupsen/logrus/@v/v1.2.0.info: net/http: TLS handshake timeout
go: finding github.com/pkg/errors v0.8.0
go: gopkg.in/mgo.v2@v2.0.0-20160818020120-3f83fa500528: Get https://goproxy.io/gopkg.in/mgo.v2/@v/v2.0.0-20160818020120-3f83fa500528.info: net/http: TLS handshake timeout
go: github.com/go-check/check@v0.0.0-20161208181325-20d25e280405: Get https://goproxy.io/github.com/go-check/check/@v/v0.0.0-20161208181325-20d25e280405.info: net/http: TLS handshake timeout
go: github.com/mitchellh/mapstructure@v1.1.2: Get https://goproxy.io/github.com/mitchellh/mapstructure/@v/v1.1.2.info: net/http: TLS handshake timeout
go: finding github.com/go-openapi/spec v0.0.0-20170811033243-3faa0055dbbf
go: finding github.com/go-openapi/errors v0.0.0-20170426151106-03cfca65330d
go: gopkg.in/warnings.v0@v0.1.2: Get https://goproxy.io/gopkg.in/warnings.v0/@v/v0.1.2.info: net/http: TLS handshake timeout
go: finding github.com/mailru/easyjson v0.0.0-20170902151237-2a92e673c9a6
go: finding github.com/spf13/afero v1.2.2
go: finding github.com/go-openapi/loads v0.0.0-20170520182102-a80dea3052f0
go: finding github.com/go-openapi/runtime v0.0.0-20170901133030-bf2ff8f71507
go: github.com/go-openapi/loads@v0.0.0-20170520182102-a80dea3052f0: Get https://goproxy.io/github.com/go-openapi/loads/@v/v0.0.0-20170520182102-a80dea3052f0.info: net/http: TLS handshake timeout
go: finding github.com/spf13/cobra v0.0.0-20181021141114-fe5e611709b0
go: gopkg.in/gcfg.v1@v1.2.3: Get https://goproxy.io/gopkg.in/gcfg.v1/@v/v1.2.3.info: net/http: TLS handshake timeout
go: github.com/go-openapi/errors@v0.0.0-20170426151106-03cfca65330d: Get https://goproxy.io/github.com/go-openapi/errors/@v/v0.0.0-20170426151106-03cfca65330d.info: net/http: TLS handshake timeout
go: github.com/mailru/easyjson@v0.0.0-20170902151237-2a92e673c9a6: Get https://goproxy.io/github.com/mailru/easyjson/@v/v0.0.0-20170902151237-2a92e673c9a6.info: net/http: TLS handshake timeout
go: github.com/spf13/afero@v1.2.2: Get https://goproxy.io/github.com/spf13/afero/@v/v1.2.2.info: net/http: TLS handshake timeout
go: github.com/pkg/errors@v0.8.0: Get https://goproxy.io/github.com/pkg/errors/@v/v0.8.0.info: net/http: TLS handshake timeout
go: github.com/stretchr/testify@v1.2.2: Get https://goproxy.io/github.com/stretchr/testify/@v/v1.2.2.info: net/http: TLS handshake timeout
go: github.com/go-openapi/runtime@v0.0.0-20170901133030-bf2ff8f71507: Get https://goproxy.io/github.com/go-openapi/runtime/@v/v0.0.0-20170901133030-bf2ff8f71507.info: net/http: TLS handshake timeout
go: github.com/asaskevich/govalidator@v0.0.0-20170903095215-73945b6115bf: Get https://goproxy.io/github.com/asaskevich/govalidator/@v/v0.0.0-20170903095215-73945b6115bf.info: net/http: TLS handshake timeout
go: github.com/go-openapi/spec@v0.0.0-20170811033243-3faa0055dbbf: Get https://goproxy.io/github.com/go-openapi/spec/@v/v0.0.0-20170811033243-3faa0055dbbf.info: net/http: TLS handshake timeout
go: finding github.com/gorilla/mux v1.5.0
go: finding github.com/PuerkitoBio/purell v0.0.0-20170829232023-f619812e3caf
go: finding github.com/go-openapi/swag v0.0.0-20170606142751-f3f9494671f9
go: finding github.com/valyala/fasthttp v1.3.0
go: finding github.com/willf/bitset v0.0.0-20190228212526-18bd95f470f9
go: finding github.com/pborman/uuid v0.0.0-20180122190007-c65b2f87fee3
go: finding github.com/spf13/jwalterweatherman v1.1.0
go: finding github.com/spf13/viper v1.4.0
go: github.com/pborman/uuid@v0.0.0-20180122190007-c65b2f87fee3: Get https://goproxy.io/github.com/pborman/uuid/@v/v0.0.0-20180122190007-c65b2f87fee3.info: net/http: TLS handshake timeout
go: github.com/spf13/cobra@v0.0.0-20181021141114-fe5e611709b0: Get https://goproxy.io/github.com/spf13/cobra/@v/v0.0.0-20181021141114-fe5e611709b0.info: net/http: TLS handshake timeout
go: github.com/spf13/jwalterweatherman@v1.1.0: Get https://goproxy.io/github.com/spf13/jwalterweatherman/@v/v1.1.0.info: net/http: TLS handshake timeout
go: github.com/willf/bitset@v0.0.0-20190228212526-18bd95f470f9: Get https://goproxy.io/github.com/willf/bitset/@v/v0.0.0-20190228212526-18bd95f470f9.info: net/http: TLS handshake timeout
go: github.com/valyala/fasthttp@v1.3.0: Get https://goproxy.io/github.com/valyala/fasthttp/@v/v1.3.0.info: net/http: TLS handshake timeout
go: github.com/go-openapi/swag@v0.0.0-20170606142751-f3f9494671f9: Get https://goproxy.io/github.com/go-openapi/swag/@v/v0.0.0-20170606142751-f3f9494671f9.info: net/http: TLS handshake timeout
go: github.com/PuerkitoBio/purell@v0.0.0-20170829232023-f619812e3caf: Get https://goproxy.io/github.com/%21puerkito%21bio/purell/@v/v0.0.0-20170829232023-f619812e3caf.info: net/http: TLS handshake timeout
go: github.com/gorilla/mux@v1.5.0: Get https://goproxy.io/github.com/gorilla/mux/@v/v1.5.0.info: net/http: TLS handshake timeout
go: github.com/spf13/viper@v1.4.0: Get https://goproxy.io/github.com/spf13/viper/@v/v1.4.0.info: net/http: TLS handshake timeout
go: error loading module requirements
chmod: cannot access '/root/go/src/github.com/dragonflyoss/Dragonfly/bin/linux_amd64/supernode': No such file or directory
BUILD: supernode in /root/go/src/github.com/dragonflyoss/Dragonfly/bin/linux_amd64/supernode

### Ⅵ. Environment:

- dragonfly version: master
- OS Ubuntu
- Kernel - Linux My-machine 4.15.0-52-generic #56-Ubuntu SMP Tue Jun 4 22:49:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: Go & Docker
- Others: I think master is getting failed to build the clients (dfget & dfdaemon) also.

**Comment by Starnop** [comment]
Could you please make a check for your network connection?

**Comment by tirupatibg** [comment]
@Starnop I don't have any issue with network connection. I was able to build the client code on the same machine with version 0.3.x

**Comment by Starnop** [comment]
> @Starnop I don't have any issue with network connection. I was able to build the client code on the same machine with version 0.3.x

The version 0.3.x was written by java and 0.4.x was written by golang. And now the master branch manage the dependency with go mod which will download the dependency according to the go.mod and go.sum files. So please make sure that you can success to ping `https://goproxy.io`.

**Comment by yeya24** [comment]
@tirupatibg  Did you still have problems building dragonfly?
It seems a problem from goproxy.io. We set the environment variable GORPOXY to https://goproxy.io at https://github.com/dragonflyoss/Dragonfly/blob/c5d08731c856c3f71d09eb0a0dc7567754f7a0ed/Makefile#L26  and https://github.com/dragonflyoss/Dragonfly/blob/c5d08731c856c3f71d09eb0a0dc7567754f7a0ed/hack/env.sh#L29 
Can you please have a try to unset this environment variable or set this to other go mod proxy, such as https://proxy.golang.org?

**Comment by Starnop** [comment]
Long-time no reply. Close it now.
