### ISSUE TITLE
What is the possibly of the client connects to the peer client (not super node) to download the file.

### ISSUE THREAD

**Issue by tirupatibg** [dragonflyoss/Dragonfly#697]
## Question
How much time the file will be stored (or in memory) in the client to serve the peer client.
Or what is the expiration of the file at the client side to serve to peer node? 

My observation is that, once the first client download the file, it keep file in-memory for certain time (10 min), with this duration when other client requests the same file, then this file will be served.

What if the first client goes down?

**Comment by Starnop** [comment]
FYI. https://github.com/dragonflyoss/website/blob/8a048f98c6315ff60ae14854579e5fb8147f6905/docs/en-us/faq.md#why-does-dfget-still-keep-running-after-fileimage-distribution-finished

**Comment by Starnop** [comment]
Would you please close this issue if you have no more related questions? THX>

**Comment by Starnop** [comment]
Long-time no reply. Close it now.
