### ISSUE TITLE
Can I deploy the super node in the cloud? 

### ISSUE THREAD

**Issue by tirupatibg** [dragonflyoss/Dragonfly#698]
## Question
1. Can i deploy the super node in the cloud? My use case is something like super node would be hosted in the cloud, the very first download of a file should be serve from the super node. and subsequent downloads should be served from peer clients. Here my main usecase is just to reduce the internet bandwidth as well as I don't want to deploy the super node in the customer place.

**Comment by Starnop** [comment]
I think the answer is yes. However, the supernode with version 0.4.x is refactored by golang not long ago and it's not ready for production usage. 

If you use a scene that does not require high availability, and welcome to experience the golang version. And it's much better to give us some feedback. 😄  If not, it's recommended to  0.3.x with java firstly and wait for gray when the golang version is ready for production usage.  Of course, we will do the compatible work well.

**Comment by Starnop** [comment]
Long-time no reply. Close it now.
