### ISSUE TITLE
How can I use dfget in the physical machine when I install dfget by docker?

### ISSUE THREAD

**Issue by YCait** [dragonflyoss/Dragonfly#751]
## Question

I install dfget and supernode by docker. If I use dfget directly in docker, in this case , the dfclient' register ip is the ip in docker, so it cannot connect to other peers(which are launched by docker too ) on the different machine. How can I solve this problem? I think using dfget in the physical machine not in the docker may solve this problem, but how can I do that?

**Comment by YCait** [comment]
And will supernodes in the cluster automatically synchronize files?

**Comment by zgfh** [comment]
@YCait you can try `--net=host` https://docs.docker.com/engine/reference/commandline/run/#connect-a-container-to-a-network---network

**Comment by Starnop** [comment]
> And will supernodes in the cluster automatically synchronize files?

What's that mean? If you are talking about multi supernodes which specified by the dfget, and then that may will disappointed you. There is no relationship between supernodes. 

However, we are doing the HA of supernode. FYI> https://github.com/dragonflyoss/Dragonfly/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+HA
