### ISSUE TITLE
Supernode should add clear process

### ISSUE THREAD

**Issue by xzy256** [dragonflyoss/Dragonfly#755]
## Why
`dfclient` will clear repo data after 3 mins, howerver `supernode` hasn't clear process . It extremely easy cause disk overflow.

## could be
1. Regular cleaning
2. Must have rules : clear long-term non-access images except access frequently images
3. New pull disk overflow error, clear forcibly

**Comment by Starnop** [comment]
We are doing it in the pr #779. Welcome to have a review.
