### ISSUE TITLE
we should print log to console by default not a file

### ISSUE THREAD

**Issue by zgfh** [dragonflyoss/Dragonfly#788]
## Why you need it?

we should print log to console by default not a file, it will be easy to debug with ide or run Dragonfly with container

## How it could be?

default print log to console
if use config a logfile param, then print log to file

**Comment by yeya24** [comment]
Thanks for your report and I totally agree with you.
But this issue duplicates with https://github.com/dragonflyoss/Dragonfly/issues/651. Also there is already a PR for this feature. https://github.com/dragonflyoss/Dragonfly/pull/783.
So  I will close this.
