### ISSUE TITLE
bug: dfgettask should be updated to success status when finish downloading

### ISSUE THREAD

**Issue by yeya24** [dragonflyoss/Dragonfly#792]
### Ⅰ. Issue Description
Currently, when dfget download successfully, it will just exist. So this dfgettask in supernode will remain the status 'RUNNING' until it is deleted. I think this dfgettask should be updated to 'SUCCESS' status when the download is finished. 

### Ⅱ. Describe what happened
dfgettask in supernode will remain the status 'RUNNING' even if the download is successfully finished.

### Ⅲ. Describe what you expected to happen
Dfget will update the status of dfgettask to 'SUCCESS'.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- dragonfly version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by Starnop** [comment]
I think we can update the status [here]( https://github.com/dragonflyoss/Dragonfly/blob/master/supernode/daemon/mgr/task/manager_util.go#L318). WDYT?

**Comment by yeya24** [comment]
> I think we can update the status [here](https://github.com/dragonflyoss/Dragonfly/blob/master/supernode/daemon/mgr/task/manager_util.go#L318). WDYT?

This place LGTM. I will open PR soon after I test it in my local env.
