### ISSUE TITLE
Some questions about pieceHeader

### ISSUE THREAD

**Issue by hegnee** [dragonflyoss/Dragonfly#796]
## Question

```
func getContentLengthByHeader(pieceHeader uint32) int32 {
	return int32(pieceHeader & 0xffffff)
}
```
why is contentLength (` pieceHeader & 0xffffff` )and  not ` pieceHeader & 0xffffffff`? 
```
func getPieceHeader(dataSize, pieceSize int32) uint32 {
	return uint32(dataSize | (pieceSize << 4))
}
```
why  is the value of `PieceHeadSize`   `real data size | (piece size << 4)` ?

**Comment by lowzj** [comment]
```
=================================================================
PIECE HEADER (32 BITS)
=================================================================
+---------------+---------------+---------------+---------------+
|    BYTES[0]   +    BYTES[1]   +    BYTES[2]   +    BYTES[3]   +
+---------------+---------------+---------------+---------------+
|0 1 2 3 4 5 6 7|0 1 2 3 4 5 6 7|0 1 2 3 4 5 6 7|0 1 2 3 4 5 6 7|
+---------------+---------------+---------------+---------------+
        |4 5 6 7|<---------------- real dataSize -------------->|
        +-------+                    UNIT: byte
        (pieceSize & 0xf00000) << 4
        UNIT: MB
```

* `dataSize` is the real content length of a piece, its value is less than the value of `pieceSize`.
* The value of `pieceSize` of a task is fixed, integral multiple of `2^20`, and between `4MB` and `15MB`, so `pieceSize == pieceSize & 0xf00000`. So we can use 4 bits(`BYTES[0][4,7]` of `pieceHeader`) to represent it.
* The lowest 24 bits represent `dataSize`, so we can get the equation  `dataSize = pieceHeader & 0xffffff`.
* So `pieceHeader = dataSize | ((pieceSize & 0xf00000)<<4)` equals to `pieceHeader = dataSize | (pieceSize << 4)` 
* The first 4 bits of `pieceHeader` are for future using, they are not used for now.

**Comment by hegnee** [comment]
@lowzj  I understand, thank you for your answer!

**Comment by Starnop** [comment]
> ```
> =================================================================
> PIECE HEADER (32 BITS)
> =================================================================
> +---------------+---------------+---------------+---------------+
> |    BYTES[0]   +    BYTES[1]   +    BYTES[2]   +    BYTES[3]   |
> +---------------+---------------+---------------+---------------+
> |0 1 2 3 4 5 6 7|0 1 2 3 4 5 6 7|0 1 2 3 4 5 6 7|0 1 2 3 4 5 6 7|
> +---------------+---------------+---------------+---------------+
>         |4 5 6 7|<---------------- real dataSize -------------->|
>         +-------+                    UNIT: byte
>         (pieceSize & 0xf00000) << 4
>         UNIT: MB
> ```
> 
> * `dataSize` is the real content length of a piece, its value is less than the value of `pieceSize`.
> * The value of `pieceSize` of a task is fixed, integral multiple of `2^20`, and between `4MB` and `15MB`, so `pieceSize == pieceSize & 0xf00000`. So we can use 4 bits(`BYTES[0][4,7]` of `pieceHeader`) to represent it.
> * The lowest 24 bits represent `dataSize`, so we can get the equation  `dataSize = pieceHeader & 0xffffff`.
> * The first 4 bits of `pieceHeader` are for future using, they are not used for now.
> * So `pieceHeader = dataSize | ((pieceSize & 0xf00000)<<4)` equals to `pieceHeader = dataSize | (pieceSize << 4)`

Maybe we can add this answer to the source code as comments. In addition, we should add it as a FAQ item. WDYT? @lowzj
