### ISSUE TITLE
[bug] gc task function always return true

### ISSUE THREAD

**Issue by yeya24** [dragonflyoss/Dragonfly#845]
### Ⅰ. Issue Description
https://github.com/dragonflyoss/Dragonfly/blob/8e41c83bebd770279728c251f0f916d58569a96d/supernode/daemon/mgr/gc/gc_task.go#L61-L87
This function always return true. So this part is kind of meaningless because it never return false.
https://github.com/dragonflyoss/Dragonfly/blob/8e41c83bebd770279728c251f0f916d58569a96d/supernode/daemon/mgr/gc/gc_task.go#L52 

Maybe it is not a bug but I hope we can deal with this more elegantly.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- dragonfly version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by SataQiu** [comment]
Resolved.
/close

**Comment by SataQiu** [comment]
I can't close this. :( @yeya24
