### ISSUE TITLE
Enable staticcheck for this repo

### ISSUE THREAD

**Issue by SataQiu** [dragonflyoss/Dragonfly#848]
## Why you need it?

`staticcheck` is useful, it can help to do go static analysis, detect bugs, performance issues, and much more. A lot of repos use `staticcheck` as a code check tool.

Ref: https://github.com/dominikh/go-tools

If this makes sense, I'd like to help introduce the `staticcheck`.

**Comment by allencloud** [comment]
> If this makes sense, I'd like to help introduce the staticcheck.

I totally support that we need this. Code quality is one of the most important things we emphasize.

**Comment by SataQiu** [comment]
OK! @allencloud 
I will send a PR to deal with this. :smile:
