### ISSUE TITLE
What is the purpose of time.Sleep in function pullPieceTask of P2PDownloader?

### ISSUE THREAD

**Issue by zhm9484** [dragonflyoss/Dragonfly#864]
## Question

I wonder that why there is time.Sleep in function pullPieceTask. It may slows down the whole download process.
Is it meant to reduce the pressure on supernode?

Thanks for answering!

https://github.com/dragonflyoss/Dragonfly/blob/3cbac7639dec3cb25a7c3c28ff0ac12558be5092/dfget/core/downloader/p2p_downloader/p2p_downloader.go#L232-L247

**Comment by lowzj** [comment]
It just sleep when there're no available piece to download in the p2p network. The clients should wait a moment for supernode to download a piece data from source file server.

**Comment by zhm9484** [comment]
> It just sleep when there're no available piece to download in the p2p network. The clients should wait a moment for supernode to download a piece data from source file server.

Thanks for replying! 
So is it possible to shorten the sleeping duration in order to reduce the latency?

**Comment by lowzj** [comment]
The sleep time maybe long when we download a small file. It can be optimized to adjust the sleep time according to the file length and download speed.

**Comment by Starnop** [comment]
> The sleep time maybe long when we download a small file. It can be optimized to adjust the sleep time according to the file length and download speed.

I have finished it in the PR #815 BTW. PLAT. THX
