### ISSUE TITLE
[Help wanted] feature: support dfget configuration items support formats such as 20M/m/K/k

### ISSUE THREAD

**Issue by Starnop** [dragonflyoss/Dragonfly#879]
## Why you need it?

The users have to convert config values to bytes when users want to config the dfget item such as `localLimit`, `totalLimit` and `minRate`. That's not user-friendly. So we should make these items support formats such as `20M/m/K/k`.

## Other related information

Please pay attention to [this PR](https://github.com/dragonflyoss/Dragonfly/pull/802#discussion_r320548118).

**Comment by yeya24** [comment]
I have already implemented it, I will open a PR after I finish the tests.
