### ISSUE TITLE
dfget config and properties are duplicate

### ISSUE THREAD

**Issue by yeya24** [dragonflyoss/Dragonfly#933]
Currently in the code of dfget, we use two structs, one is Properties https://github.com/dragonflyoss/Dragonfly/blob/0ba7a247f768439cba53072d6db05f7e3cf96c9a/dfget/config/config.go#L59 and another is Config https://github.com/dragonflyoss/Dragonfly/blob/0ba7a247f768439cba53072d6db05f7e3cf96c9a/dfget/config/config.go#L142. 

These two structs are kind of duplicate, we should only keep one of them.

**Comment by Starnop** [comment]
I think we can embed the struct `Properties `  into `config`. WDYT? @yeya24 @tanjunchen

**Comment by yeya24** [comment]
> I think we can embed the struct `Properties ` into `config`. WDYT? @yeya24 @tanjunchen

It is OK for embedding it. But it is still duplicate, right? Why not just remove one now.

**Comment by inoc603** [comment]
`Properties` seems to be designed for a config file. No matter how we decided to handle this, we should be careful and clear about what can be configured from a file, and from cli parameters. Dfdaemon experienced a similar situation for config a while back.

**Comment by yeya24** [comment]
> `Properties` seems to be designed for a config file. No matter how we decided to handle this, we should be careful and clear about what can be configured from a file, and from cli parameters. Dfdaemon experienced a similar situation for config a while back.

This seems quite reasonable. If we use one struct like config to represent the whole config both from cli params and config files, we can still use like 'yaml:'-'' to avoid some fields exposing. But this will increase confusion, not as clear as before

**Comment by yeya24** [comment]
Since #936 , close this issue
