### ISSUE TITLE
30 clients pull images，all data traffic was downloaded from supernode.Should dfget download the pieces of file from other peers?

### ISSUE THREAD

**Issue by KeepCaim** [dragonflyoss/Dragonfly#939]
## Question
1.    30 nodes parallel pull images, the image is 88M, It looks like all the data traffic goes through supernode. Should dfget download the pieces of file from other peers?
Below is the iftop for supernode:
TX:             cum:   2.40GB   peak:    159Mb  rates:   9.64Kb  9.63Mb  92.3Mb
RX:                     458MB           1.01Mb           7.86Kb  71.9Kb   600Kb
TOTAL:                 2.85GB            160Mb           17.5Kb  9.70Mb  92.9Mb

2.    first,i pull a image,  docker rmi image , then pull the same image again, supernode will trigger CDN to download the image again, all data  was downloaded from harbor registry over again
Below is the iftop for supernode:
TX:             cum:   88.4MB   peak:    201Mb  rates:   1.80Kb  70.6Mb  44.2Mb
RX:                    89.0MB            281Mb            160b   15.1Mb  44.5Mb
TOTAL:                  177MB            281Mb           1.95Kb  85.7Mb  88.7Mb

**Comment by Starnop** [comment]
Could you please check that whether you get the same taskID when you pull the same image again?

**Comment by KeepCaim** [comment]
Yes, I found the same data taskid is different  when i pull the same image again.
Like this, 

585M	./download/2f2
12K	./download/999
16K	./download/491
12K	./download/1d9
20K	./download/4b5
12K	./download/c7c
17M	./download/e6a
12K	./download/dd9
585M	./download/139

**Comment by KeepCaim** [comment]
@Starnop hi,  I think that's the question, but where can i config it, in dfdaemon.yml ? and how should I configure it.

**Comment by KeepCaim** [comment]
Unfortunately, I didn't find any help documents

**Comment by Starnop** [comment]
Sorry for delay to merge related PR. And you can config it in dfdaemon.yml. FYI https://github.com/dragonflyoss/Dragonfly/blob/master/dfdaemon/config/config.go#L44

**Comment by KeepCaim** [comment]
Unique identification of  images'blob is sha256 value that in url's path not param.
 Like this : 
GET /harbor-registry-private-bjyt/docker/registry/v2/blobs/sha256/21/21d413ed22b8dbc698807e746aa7f5fa8e4332da6d7bd2f8abffa793aa7c0290/data?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=haha-wYpr8s8iPH6tw1P3t7VR%2F20190919%2Frq-bjyt-s3%2Fs3%2Faws4_request&X-Amz-Date=20190919T093113Z&X-Amz-Expires=1200&X-Amz-SignedHeaders=host&X-Amz-Signature=bc86d14f8e546c4e4d7dbc196c9064ebb35bafa1e5b529b60af5ee5dd3ff555f HTTP/1.1

how should I do it.

**Comment by Starnop** [comment]
For your example, I think the value of `X-Amz-Date` is different for each http request.
So what you should do is to add the `X-Amz-Date` as the value of the `filter` param.

```
 dfget_flags: [ ......, "-f","X-Amz-Date",......]
......
```

**Comment by KeepCaim** [comment]
no, this doesn't work, I have verified. I think the query param for the same blob should be the same,this will generate the same taskid, but  there is no such parameter.

**Comment by KeepCaim** [comment]
Now, I get it. thanks
