### ISSUE TITLE
How can I change the download port of supernode?

### ISSUE THREAD

**Issue by YCait** [dragonflyoss/Dragonfly#950]
## Question

I'm running supernode built by docker image dragonflyoss/supernode:0.4.3, can i change 8001 port with other port?

**Comment by Starnop** [comment]
FYI https://github.com/dragonflyoss/Dragonfly/blob/master/FAQ.md#can-i-use-self-specified-ports-for-dragonfly

**Comment by yeya24** [comment]
@YCait Does it solve your problem? I will close this issue now and feel free to reopen it if you have any other related questions.
