### ISSUE TITLE
running piece concurrent update wrong

### ISSUE THREAD

**Issue by liudechi7** [dragonflyoss/Dragonfly#976]
### Ⅰ. Issue Description
There is a concurrency problem in this area. If a routine deletes the key, the next one goes to read and causes the key to not exist.
	
`return dstPIDMap.Remove(pieceNumString)`

// 这个地方存在并发问题，如果一个routine删除了key，下一个在去读取导致key不存在 ，返回错误后，导致客户端异常

### Ⅳ. How to reproduce it (as minimally and precisely as possible)
1.
2.
3.
### Ⅵ. Environment:
- dragonfly version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

***!!!!WE STRONGLY ENCOURAGE YOU TO DESCRIBE YOUR ISSUE IN ENGLISH!!!!***

**Comment by Starnop** [comment]
Obviously, you have a deep understanding of the source code. 👍 

However, let's have a look at the source code carefully:

```
// updateRunningPiece updates the relationship between the running piece and srcCID and dstPID,
// which means the info that records the pieces being downloaded from dstPID to srcCID.
func updateRunningPiece(dstPIDMap *syncmap.SyncMap, srcCID, dstPID string, pieceNum, pieceStatus int) error {
	pieceNumString := strconv.Itoa(pieceNum)
	if pieceStatus == config.PieceRUNNING && !stringutils.IsEmptyStr(dstPID) {
		return dstPIDMap.Add(pieceNumString, dstPID)
	}

	if _, err := dstPIDMap.Get(pieceNumString); err != nil {
		if errortypes.IsDataNotFound(err) {
			return nil
		}
		return err
	}

	return dstPIDMap.Remove(pieceNumString)
}
```

And you will find that the concurrent threads will not get errors even if failed to load `pieceNumString` and return nil instead. 

WDYT?

**Comment by liudechi7** [comment]
> 	return dstPIDMap.Remove(pieceNumString)

`// Remove deletes the key-value pair from the mmap.
// The ErrEmptyValue error will be returned if the key is empty.
// And the ErrDataNotFound error will be returned if the key cannot be found.
func (mmap *SyncMap) Remove(key string) error {
	if stringutils.IsEmptyStr(key) {
		return errors.Wrap(errortypes.ErrEmptyValue, "key")
	}

	if _, ok := mmap.Load(key); !ok {
		return errors.Wrapf(errortypes.ErrDataNotFound, "failed to get key %s from map", key)
	}

	mmap.Delete(key)
	return nil
}`
remove function is key problem
