### ISSUE TITLE
If the file source is updated more frequently (e.g. once an hour), dfget will have files that cannot be updated in time.

### ISSUE THREAD

**Issue by huerlei** [dragonflyoss/Dragonfly#993]
## Question

我在用dfget 下载文件的时候，发现如果文件源更新频率比较高，（例如1小时更新一次），dfget 下载该文件的时间大约为45分钟，会存在一段时间一直同步老的文件的情况，请问这个正常吗，怎么可以解决

**Comment by lowzj** [comment]
同一个url指向的文件资源是变化的话，可以通过指定`dfget`的`-i`参数来区分开

**Comment by Starnop** [comment]
Releated issue: #978
