### ISSUE TITLE
镜像仓库回源问题 | Return of Mirror Warehouse

### ISSUE THREAD

**Issue by ftlynx** [dragonflyoss/Dragonfly#995]
## Question
使用dragonfly做镜像分发。supernode有CDN的作用，那么回源我认为是supernode去做，通过查看连接但是我发现除了supernode，dfdaemon进程也会去连接仓库地址，我看文档上面说dfdaemon会拦截docker的请求，请问这个是什么情况下会这样呢?
root@host-192-168-55-107 dfclient]# netstat -antp | grep 52.206.19.194:443
tcp        0      0 192.168.55.107:47260    52.206.19.194:443       ESTABLISHED 22508/supernode
tcp        0      0 192.168.55.107:47204    52.206.19.194:443       ESTABLISHED 10219/dfdaemon

**Comment by lowzj** [comment]
拉取镜像的整个过程分为：
1. 认证
2. 获取image manifests
3. 下载 image layer

其中1/2不涉及文件下载，是由`dfdaemon`请求仓库；第3步，镜像层下载由`dfdaemon`调用`dfget`进行p2p下载，这时候supernode若本地无缓存则回源到仓库。

**Comment by ftlynx** [comment]
了解了。谢谢。
